### ISSUE TITLE
Google Calendar Support

### ISSUE THREAD

**Issue by dbarenholz** [davish/obsidian-full-calendar#1]
Hi! 

I'd absolutely love some google calendar support. Will be happy to help out with coding as well!
Specifically, I'd like the same way that todoist supports gcal integration:
* 1 way sync FROM gcal TO obsidian => Obsidian is just a view, and non-editable.
* 1 way sync FROM obsidian TO gcal => Any event you create in obsi plugin is pushed to a calendar in gcal, but changes in gcal aren't propagated back.
* 2 way sync: obsidian and gcal are kept in sync with each other <-- my preferred method, probably also the hardest to implement.

**Comment by StefanoRausch** [comment]
It is on the roadmap, but yes, a two-way sync would be fantastic!

**Comment by davish** [comment]
Thanks for submitting this issue, @dbarenholz! Luckily, your first proposal is quite trivial since we can rely on [Full Calendar's support for GCal feeds](https://fullcalendar.io/docs/google-calendar). I'm planning on tackling this right after adding support for multiple calendars.

I also think there's another sync level, a one way *import* (or dump) from Google Calendar into Obsidian. It would require reading directly from the GCal API and so would be a stepping stone on the way to two-way sync, and would be useful for those who want to migrate from GCal wholesale.

Would you be alright with me filing separate issues for each of these sync options? I'll link back to this issue in each of them.

**Comment by scriptor-dga** [comment]
Why would you use a less functional Google Calendar embedded in Obsidian instead of just using Google Calendar? 😅

**Comment by tylerwince** [comment]
Regarding Google Calendar (but also other sync options for calendars) I think it could be huge to sync attendees as well as all the other event data. 

The way I think attendees should be handled, however, may be a bit unique, so I'm curious what others think...

It would be amazing if the plugin could take the email address on the event, search for a page which has a matching email attribute, and automatically create a link to that page in the calendar event page. 

## Example: 

If I have a page called `Tyler Wince.md` and it has the following contents:

```markdown
---
email: tyler@email.com
---

Some notes about Tyler here
```

Then a calendar event which contains `tyler@email.com` as an attendee would automatically link to the `Tyler Wince.md` page.

Hopefully this makes sense... 😅

**Comment by davish** [comment]
Documentation on read-only sync in release `0.2.0`: https://github.com/davish/obsidian-full-calendar#add-a-google-calendar

**Comment by vanadium23** [comment]
Google has a secret link for .ics format. Can we have integrations with the feature instead of making a calendar public?

![image](https://user-images.githubusercontent.com/2872741/154836081-46f6fcff-4e0a-4b7a-9463-aaf038258931.png)

**Comment by wenlzhang** [comment]
> Google has a secret link for .ics format. Can we have integrations with the feature instead of making a calendar public?

It would be great if something like this can be used to not make the calendars in Google public.

**Comment by davish** [comment]
Thanks for the feedback! I agree that making the calendar public isn't ideal. I think that when #2 is ready to go, I'll also recommend syncing GCal through the private .ics link.

**Comment by davish** [comment]
Hi all -- closing this thread in favor of more atomic Issues tracking specific features that were requested here: #24, #25, #26, #27
