### ISSUE TITLE
Feature Request: Cleaner, More User-Friendly 'New Event' Screen

### ISSUE THREAD

**Issue by Welding-Torch** [davish/obsidian-full-calendar#10]
# The 'New Event' Screen
![image](https://user-images.githubusercontent.com/46340124/154450996-7d5025e9-8c60-46a4-b92e-acf0e0b54546.png)

## Requests:
1. **Have 'Calender Widget' display by default** - So I like to follow a policy of #each_click_counts. If we can reduce the number of times a user has to click on the screen, it improves the user experience. Now, if I press 'Ctrl+P' and type 'New Event' and hit 'Enter', that's a really good start to the workflow. However, if I'm going to pick a date I'm almost certainly going to click the little 📅Calender icon next to the input box. Here's my suggestion: Have the Calender-Input-Widget display by default on the 'New Event' screen. It reduces a click and adds a visual. 
![full-calender-annot - Copy](https://user-images.githubusercontent.com/46340124/154454632-b8ea3b81-1775-46a1-ae67-782ce9bfaad5.jpg) *Mockup image included for demonstration purposes . Made in MS Paint to demonstrate how it would look like.*

2. **Remove 'Recurring Event' from 'New Event' screen** - I only add a recurring event once every 7 years, I don't need to see this every time I want to create a new event. Find some other place to keep it. Keep the 'New Event' screen cleaner. 
![full-calender-annot - Copy (2)](https://user-images.githubusercontent.com/46340124/154454591-07547f9b-bdb4-43e3-a4d6-53f3597da0d4.png)

❤️ Thank you

**Comment by davish** [comment]
Thanks so much for the feedback and the UI mockups! I'm certainly not the most happy with the current event modal -- I'll take your feedback into consideration when updating it. One piece of low-hanging fruit is shifting the auto-focus from the title to the datepicker. I agree that that would save some time.

**Comment by davish** [comment]
In the spirit of more atomic issues, I filed #29 and #30 for these two suggestions, and am closing this issue.
