### ISSUE TITLE
Frontmatter of a created event

### ISSUE THREAD

**Issue by menagerie198** [davish/obsidian-full-calendar#100]
* Happy to delete or move if this is not appropriate for here...

Would putting additional `key: values` in the frontmatter of an event note, cause any problems down the line in FC? Would it confuse FC or make it the event non-functional?

**Comment by davish** [comment]
The plugin will ignore any extra frontmatter entries, and will not overwrite them. I don't think the parser is smart enough to deal with key/value pairs that take up multiple lines. So instead of
```
arraykey:
  - value
  - value
  - value
```
You should write
```
arraykey: [value, value, value]
```

**Comment by davish** [comment]
I should add a note that we might add new frontmatter fields to enable two-way sync and other features down the line. And issue #70 is something I plan to work on, although any migration process would need to have a way to fail gracefully.

**Comment by davish** [comment]
I'm labeling this as a question and marking it answered by closing it, but please free to follow up if you have another question :)
