### ISSUE TITLE
[bug] External link of calendar notes will not be updated if you drag the event to other dates in calendar view

### ISSUE THREAD

**Issue by Ravenclawer** [davish/obsidian-full-calendar#102]
**Describe the bug**
1. create a event using full calendar plugin , may be "2022-04-26 test"
2. open a note and create a wikilink to the note generated by the event. [[2022-04-26 test]]
3. move the  event in full calendar to 2022-04-27, the name of the event note will be automatically changed to "2022-04-27"
4. the wikilink in the note will not change to "2022-04-27 test" but stay as "2022-04-26 test", causing the loss of link between the note and the event 
**To Reproduce**
1. create a event using full calendar plugin , may be "2022-04-26 test"
2. open a note and create a wikilink to the note generated by the event. [[2022-04-26 test]]
3. move the  event in full calendar to 2022-04-27, the name of the event note will be automatically changed to "2022-04-27"
4. the wikilink in the note will not change to "2022-04-27 test" but stay as "2022-04-26 test", causing the loss of link between the note and the event 

**Expected behavior**
the wikilink in other notes will be update when the name of the event note changed 

**Screenshots**

**Console Errors**
Go to `View->Toggle Developer Tools` and open up the JavaScript console, reproduce your bug, and copy/paste any logs you see there.

**Device info (please complete the following information):**
 - Plugin Version [e.g. `0.1.3`]
- windows 0.14.6
- 0.6.1
**Additional context**

**Comment by davish** [comment]
Thanks for marking as a duplicate. This is definitely a bug that I'll look to get too soon -- I'll close this issue, though, since it is tracked by #64 as you wrote.
