### ISSUE TITLE
Question/FR: Create notes fom events!

### ISSUE THREAD

**Issue by brimwats** [davish/obsidian-full-calendar#104]
Hello!

This might be possible but I cant find it in the documentation—how do I create notes from events (versus upgrading a note to an event)?

**Comment by davish** [comment]
Every event in a local calendar is stored as a note in your vault. You can open it by searching for the event title, or, from the calendar, you can click the event and then click "Open note" from the edit modal that appears.

Cheers!

**Comment by brimwats** [comment]
I guess what I wanted then was the ability to create a note from a remote calendar! Would that be possible currently? Mostly I add things to gcal and then have to make a new note in obsidian but would rather click an event from gcal in full calendar and then write a note for that! Does that make sense?

**Comment by davish** [comment]
Ah, no, that's not possible currently. The feature is being tracked in issue #40, though, and it's on my radar.
