### ISSUE TITLE
QoL tweaks

### ISSUE THREAD

**Issue by menagerie198** [davish/obsidian-full-calendar#11]
Could we have the ability to change the first day of the week (Monday/Sunday), and the time format in the timegrid/events to 24h, please?

**Comment by davish** [comment]
Great point! Thanks for filing this.

**Comment by edward-peters** [comment]
This would be terrific. Do you also have in mind to add a config to limit the hours of the day displayed to a custom setting? (E.g. 08:00-18:00)

**Comment by davish** [comment]
I'm working towards atomic issues with one request each, so I'm closing this in favor of #34, #33, and #32 which track each of these requests individually.
