### ISSUE TITLE
Cannot create event - current restriction

### ISSUE THREAD

**Issue by hermannkm** [davish/obsidian-full-calendar#121]
**Describe the bug**
When trying to create an event the second option (dropdown) is not working and "Save" cannot be applied
**To Reproduce**
1. Select command Create new event
2. Fill in title
3. Click on second line dropdown
4. Nothing happens, "Save" cannot be selected

**Expected behavior**
Dont't know exactly as I have installed it just now, never saw this working. I think this could be a selector for the calendar to use.
[](url)

**Screenshots**
<img width="547" alt="fcss1" src="https://user-images.githubusercontent.com/12869273/171112447-ff820f06-ccaa-4928-afdd-b573d5caa4a4.png">

**Console Errors**
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at EventModal.eval (plugin:obsidian-full-calendar:52799:22)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-full-calendar:66:61)
    at new Promise (<anonymous>)
    at __async (plugin:obsidian-full-calendar:50:10)
    at submit (plugin:obsidian-full-calendar:52797:42)
    at eval (plugin:obsidian-full-calendar:52214:11)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-full-calendar:66:61)
    at new Promise (<anonymous>)

**Device info (please complete the following information):**
 - OS: macOS 11.6.6
 - Plugin Version 0.6.1

**Additional context**
I have one remote calendar subscription (https://outlook.office365.com/owa/calendar/.../calendar.ics)

**Comment by hermannkm** [comment]
Sorry, read afterwards in documentation that this is a restriction in the current version. Creating an event with a local calendar (as recommended) is working flawlessly.

**Comment by Luvata** [comment]
Really looking forward to this feature, I tried Yandex CalDav and also got this problem :( @davish
