### ISSUE TITLE
Upgrade note to event does not move note to calendar folder

### ISSUE THREAD

**Issue by hermannkm** [davish/obsidian-full-calendar#123]
**Describe the bug**
If I upgrade a note to an event selecting a local calendar (which has a folder defined) the note stays where it was (e.g. in vault root). I have to move it manually to activate it as an event which I clearly want by using this command.

**To Reproduce**
1. Create note in vault root
2. Select "Upgrade note to event"
3. Select a calendar which lives in a local folder e.g. "work"
4. See nothing in calendar as note stays in root.

**Expected behavior**
Move note to calendar folder.

**Device info (please complete the following information):**
 - OS: macOS 11.6.6
 - Plugin Version 0.6.1

**Comment by davish** [comment]
"Upgrade note" has been removed as a feature, so I'll close this issue.
