### ISSUE TITLE
get time-spent report on a same-titled event/event under same subject(perhaps using yaml attributes+dataview)?

### ISSUE THREAD

**Issue by Oratoriooooo** [davish/obsidian-full-calendar#125]
Hi, I'm wondering if there is a way I can get time-spent report in a flexible way.
# use case1: events with same titles starting
I may open several events on calendar to track my progress on a TODO(therefore those events will have same title on frontpart, since we cannot have notes with same titles in a folder yet) 

this screenshot shows I did 2 edit note in a day. 
Is there a way I can get **_total time spent_** within a time range(e.g. on a day, from someday to someday...) with same entry-title(starting part)? So I can know how much time I spent on a TODO without manually calculate.
![image](https://user-images.githubusercontent.com/36411771/174778673-e29f75e4-25b7-4190-a39f-8b694814aed5.png)
# use case2: events under same subject
every event on calendar is a note with some yaml front matter. If we add some yaml attributes to indicate category, is there a way to generate time-spent report under same category within a date range? 
I assume we can do this with dataview, but I am not sure.

e.g. in this example I edited 2 entries from 2 days by adding a category in yaml. Now I want to know how many time I spent on category: Study in these 2 days. 

Is there a way to get from dataview query already, or perhaps these 2 use case provided here and above could be a feature proposal? 
![image](https://user-images.githubusercontent.com/36411771/174779585-41f349c6-0c4b-49ee-903f-881731d7c5cb.png)
![image](https://user-images.githubusercontent.com/36411771/174779625-4ef30243-8f73-4c55-8a62-7dc63546d3a6.png)

**Comment by davish** [comment]
This can likely be achieved with [Dataview](https://github.com/blacksmithgu/obsidian-dataview). Extra analysis of events like this isn't in scope for the plugin -- in fact, it's an intentional design goal that all metadata is stored as regular frontmatter so that other plugins can interoperate with Full Calendar.
