### ISSUE TITLE
Cannot get 3-day view to remain; it toggles between 7-day view.

### ISSUE THREAD

**Issue by litchaikov** [davish/obsidian-full-calendar#127]
I love this plugin, really glad it's here, as it lets me stay in Obsidian for longer.

My main issue is that _sometimes_ the interface displays a  7-day view, and sometimes it displays a 3-day view.  The 7-day view is squished up, and not great for a column in Obsidian.

![Screenshot 2022-06-24 at 14 43 23](https://user-images.githubusercontent.com/108133364/175538499-81989c04-c50b-4f52-8f6c-c1055fb2a77d.png)
 
The 3 day view is ideal. But I don't know how to toggle it, or get it so that it is always in 3 day view. 3 day is more compact and does not have giant letters for the date at the top.

Is there a way to get it set at 3 day view? Is there a reason it keeps toggling between the 2?  Thanks!!! Again, it's a fantastic plugin and I'll use it regardless of if this issue can be fixed.

**Comment by davish** [comment]
The 3 day view is toggled based on the detected width of your device. @litchaikov what kind of device are you using? If on a desktop/laptop, are you using a narrow window or pane? I would recommend using a wider pane. If you are on a mobile device, then this is a bug that the 7 day view should be visible at all.

**Comment by davish** [comment]
Closing this since it hasn't had activity in a month. Feel free to comment on it if this issue keeps happening.

**Comment by Ambursley** [comment]
Full Calendar does not completely load on mobile devices (iphone, ipad). Window remains blank no matter if I change view settings or restart
