### ISSUE TITLE
Does Google Calendar work with app specific passwords and CalDav or something else?

### ISSUE THREAD

**Issue by datavistics** [davish/obsidian-full-calendar#130]
**Describe the bug**
Does Google Calendar work with [app specific passwords](https://support.google.com/calendar/answer/37082?hl=en) and calDav or something else??

**Comment by datavistics** [comment]
@davish, any ideas?

**Comment by datavistics** [comment]
I don't have access to my secret url since it's controlled by my company.

**Comment by davish** [comment]
Hi @datavistics,

Google Calendar doesn't work with CalDAV right now, unfortunately, since the CalDAV integration authorizes users with OAuth rather than basic username/password auth. You'll need the .ics link in order to sync with GCal.

**Comment by davish** [comment]
Closing this issue with a link to the relevant documentation: https://davish.github.io/obsidian-full-calendar/calendars/ics/
