### ISSUE TITLE
Request recurring date for month and year

### ISSUE THREAD

**Issue by Rsose** [davish/obsidian-full-calendar#131]
Hi Davish
Could you please add a recurring date for each year or each month?
Because, usually the installments are per month or per year
I now have to set it to recur through the dates every weekend (so as not to forget)

Waiting for a reply
Thanks

**Comment by cja-github** [comment]
Yes please. Basically, please copy the recurring options that Google Calendar has.

**Comment by davish** [comment]
Closing this issue as a duplicate of #22
