### ISSUE TITLE
Getting "No frontmatter to edit for selected event" when clicking on any event in any view, and can't add events ("Save Event" button is black and unresponsive)

### ISSUE THREAD

**Issue by cdmoss** [davish/obsidian-full-calendar#135]
**Describe the bug**
I'm getting "No frontmatter to edit for selected event" when clicking on any event in any view. Save event does nothing when adding an event. I'm using Nextcloud caldav if that matters.

**To Reproduce**
Self explanatory

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40777533/182264049-44043cbe-321e-482b-858c-d0a43b09d347.png)

![image](https://user-images.githubusercontent.com/40777533/182264081-f8dc5eb3-7bfb-4f8d-893a-fad4fd2e1143.png)

**Console Errors**
![image](https://user-images.githubusercontent.com/40777533/182264372-0d6ccd4b-cad5-4e24-b451-186f672ea9f3.png)

**Device info (please complete the following information):**
 - OS: Ubuntu 22.04
 - Plugin Version `0.6.1`

**Additional context**

**Comment by mlieberman85** [comment]
Receiving same error here on same plugin version on MacOS

**Comment by gaxeliy** [comment]
Same error. Fedora 36

**Comment by daybreak0804** [comment]
I can see this error when I click evet that was from import Google Calendar.
2 way sync for Google Calendar ics(private url)?

**Comment by theref** [comment]
I am seeing the exact same behaviour Mac M1

**Comment by alancunha26** [comment]
Same problem

**Comment by mourdani** [comment]
same on Manjaro gnome

**Comment by greenwar** [comment]
+1 on macos sync with google calendar ics private url

**Comment by cja-github** [comment]
I get this on an ical Google Calendar feed on latest Obsidian on Windows 10

**Comment by b3rnie-s** [comment]
Same error, Google Calendar .ics private URL sync, Mac M2

**Comment by davish** [comment]
Hi all,

Thanks for trying out the Full Calendar plugin! Apologies for the silence on my end in this repository -- I've been dealing with some RSI issues and have been avoiding typing too much outside of my day job for the summer. 

This error shows up because **there is currently no way to edit/modify events that come from remote calendars**. ICS will always be one-way readonly sync, and CalDAV two-way sync is tracked in issue #25. 

If you would like to add events from within Full Calendar, make sure to add a local calendar per the [documentation here](https://davish.github.io/obsidian-full-calendar/calendars/local/). These events will not be synced with any remote source for now. I hope that helps, and feel free to tag me on this issue if any of you would like further clarification.

Cheers!

**Comment by themanofsilver** [comment]
Hi @davish. I think I may have misunderstood the capabilities of Full Calendar. From the description, I read:

> Keep your calendar in your vault! This plugin integrates the [FullCalendar](https://github.com/fullcalendar/fullcalendar) library into your Obsidian Vault so that you can keep your ever-changing daily schedule and special events and plans alongside your tasks and notes, and **_link freely between all of them_**. Each event is stored as a separate note with special frontmatter so you can take notes, form connections and add context to any event on your calendar. (emphasis added)

I understood from that that I could import (one-way is fine) my current external calendar, and either create an event note linked to a given calendar event (which would then be stored locally). From the description it seems that I should be able to link between the calendar events and notes, but currently I do not see a way to do so. I also created a local calendar, and added a note linked to a new event, and this does not appear on my calendar view. So I'm still confused about how to make this plug in do anything but display my current calendar events.

Thanks.

**Comment by Mohl** [comment]
Yeah, I was under the same impression as @themanofsilver . My perception of Obsidian is that it is first and foremost a note taking app, so I use it to take notes during meetings. Importing a calendar but having notes stored locally would be a game changer. Having two way sync is a nice addition, but what I really want to do is not to have to create a note of every meeting manually... I thought it would be as simple as "Install extention, add calendar, click on event and start typing".

**Comment by themanofsilver** [comment]
Thanks @Mohl. 

If it helps define what I am looking for (which may not be the intent of Full Calendar), I am moving to Obsidian from Craft, which has really good calendar integration to create meeting notes from calendar events. You can see what it looks like [here](https://support.craft.do/hc/en-us/articles/360021080858-Calendar-integration-Daily-Notes#h_01F73MDV0V16CAJX4MC25CDN00).  Is something like this possible with Full Calendar? Or is it on the roadmap?

**Comment by davish** [comment]
@Mohl, I'm sorry that the plugin doesn't fit your needs right now. This plugin, like Obsidian itself, is primarily focused on locally stored data. Even one-way sync with a remote calendar is not an easy thing to add. What you and @themanofsilver are asking for is tracked as a feature request in issue #40. This is definitely on the roadmap, although my first priority now is #28 and integrating the plugin with daily notes. I hope that's helpful information, and thank you for trying the plugin!

**Comment by themanofsilver** [comment]
Thanks @davish -- glad to hear this is at least envisioned on the horizon as it would be a great value-add. Agree with the comments on issue #40 in terms of the use case (link a set of meeting notes to a calendar event rather than integrating the note *in* the calendar event). I'll keep up with updates as they are avaialble!
