### ISSUE TITLE
A day planner pane on the side 

### ISSUE THREAD

**Issue by wcsolski** [davish/obsidian-full-calendar#138]
Hi, thank you for developing this plugin. I can see so much potential for this plugin. 

May I know if it's possible to create a new feature, such that daily events created for the day could be viewed on a side panel, that tracks the time of the day? Thanks! 

![image](https://user-images.githubusercontent.com/109154821/183404791-3268cdd5-834e-4d2e-8fd4-605107eb4f66.png)

**Comment by davish** [comment]
Duplicate of #51
