### ISSUE TITLE
Multi-day events

### ISSUE THREAD

**Issue by Y-a-n-i-n-a** [davish/obsidian-full-calendar#139]
Would be great to have multi-day events, this is a functionality in many calendars. E.g. if you need to block 3 days for a congress. This could also be helpful for project management - blocks of time for subtasks.
Thanks for considering it.

**Comment by GuyofM** [comment]
You can actually already do this by updating the end date of the event in the front matter.

**Comment by dkeddyk** [comment]
the attribute is named: endDate
