### ISSUE TITLE
Please clarify the error text when a event directory isn't selected, and add this step to the installation instructions

### ISSUE THREAD

**Issue by wychwitch** [davish/obsidian-full-calendar#14]
~~Hello! I just installed the plugin via BRAT and opened the calendar and it opened a empty page save for the message `Error: the events directory was not a directory. `~~

~~I checked the console but didn't see anything relevant, I'm assuming that the installation didn't create an events directory correctly? I can try and manually create one if it'll help! ~~

~~My obsidian version is 0.13.23, and I'm on 0.1.2 of this plugin. The only steps to recreate is installing the plugin via BRAT, enabling it, and opening the full calendar (via ribbon icon or command)~~

~~Thank you in advance!! Let me know if there's anything else I can do to further investigate this~~

NEVERMIND I just realized I needed to add the an events folder in the settings! Still, the error text is a bit confusing and I think it should be made clearer! Also, adding this step to the instructions will also help a lot!

**Comment by davish** [comment]
Good catch! This is buried at the bottom of the README but I'll move it to the top, and improve the error message.

**Comment by davish** [comment]
Docs have been changed and the error message was made better. I'm filing an issue though for making this more visually appealing: #31
