### ISSUE TITLE
Unable to add event with punctuation marks in the title

### ISSUE THREAD

**Issue by Y-a-n-i-n-a** [davish/obsidian-full-calendar#141]
**Describe the bug**
If I copy paste the following into the title, the event doesn't get created -> CSR Shell Final: Incorporate comments after QC Check 
If I remove : -> event is created. Same seems to be the case with ( )

Version 0.6.1

**Comment by davish** [comment]
This is a limitation of filenames in Obsidian, which cannot contain certain letters depending on the OS, so there is no plan to fix this. The work in PR #103 will make this less of an issue, since you'll be able to name events within files, rather than relying on the filename.
