### ISSUE TITLE
Multiple calendars: edit an event will reset the belonging calendar to the first one

### ISSUE THREAD

**Issue by ccll** [davish/obsidian-full-calendar#142]
**Describe the bug**
When we have multiple calendars, and we edit an event, despite the calendar the event belongs to, the dropbox will always default to the first calendar, so we need to choose the right calendar every time before saving, which is inconvenient.

**To Reproduce**
1. Create multiple calendars like Work/Personal/...
![image](https://user-images.githubusercontent.com/5366582/185027021-e486456d-5589-4a7a-82c9-a8049041d725.png)

2. Create an "test" event in the Personal calendar.
![image](https://user-images.githubusercontent.com/5366582/185027145-b080bfb5-8d3b-4d8d-bf9e-2a0952bfc484.png)
![image](https://user-images.githubusercontent.com/5366582/185027157-879b5019-7983-4573-926e-46abafd12aff.png)

3. Click on the "test" event to edit it, we can see the dropbox was reset to "Work" calendar.
![image](https://user-images.githubusercontent.com/5366582/185027305-a064cd6b-d071-4236-999e-53cacc712a8c.png)

4. Save the event and it will appear in the color of "Work" calendar.
![image](https://user-images.githubusercontent.com/5366582/185027404-fb343f25-fa7b-4c89-b3cc-87a2f835c914.png)

**Expected behavior**
Events should preserve their calendar property when editing.

**Device info (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Plugin Version: 0.6.1

**Comment by davish** [comment]
Hi @ccll, I just merged the fix for this bug and it'll be available soon for download. Thanks for your patience!
