### ISSUE TITLE
One-way, read-only sync from GCal

### ISSUE THREAD

**Issue by davish** [davish/obsidian-full-calendar#15]
First step towards bi-directional syncing is a one-way sync to let your events from GCal show up in your Obsidian Full Calendar view. Will be configurable in settings, where each calendar has a source that is either local (directory in vault) or remote (GCal feed URL).

**Comment by Hileotech** [comment]
Great to hear this!

**Comment by davish** [comment]
Here's the documentation: https://github.com/davish/obsidian-full-calendar#add-a-google-calendar

**Comment by laawn** [comment]
Is there a way to get this to work without making calendars public? Making calendars public is a privacy/security nightmare that I'm sure most people don't want to invite. Maybe utilizing the GCal's secret iCal address?
