### ISSUE TITLE
Remove the forced ending time

### ISSUE THREAD

**Issue by Jupiter79** [davish/obsidian-full-calendar#156]
I find it pretty disturbing that you HAVE to define an ending time

Example:
You create a note, and enter the date 21/10/2022 with the time 17:00 and leave the end time blank, it should create the event which goes until end of the day.

**Comment by davish** [comment]
I don't think this is intuitive behavior, personally. Events should have start and end times. I believe that if you leave off an end time then the event will default to an hour.

**Comment by Jupiter79** [comment]
This makes no sense 

E.g. you have someone's birthday in the calendar, why should you enter an exact start and end time?

**Comment by davish** [comment]
You can create an all day event by checking the "all day" checkbox in the modal, or `allDay: true` frontmatter to your event, or creating the event from the calendar in the "all day" section at the top of each column.
