### ISSUE TITLE
Button content is aligned to bottom

### ISSUE THREAD

**Issue by Tobey-Jinc** [davish/obsidian-full-calendar#165]
**Describe the bug**
The content of the buttons at the top of the calendar have their text/icons aligned to the bottom, rather than center.

**To Reproduce**
1. Open the calendar

**Expected behavior**
Based on the screenshots of the calendar, I would expect the content to be centered.

**Screenshots**
![image](https://user-images.githubusercontent.com/36495056/197647629-814f9109-3ac9-479a-a251-4454d3fd615c.png)

**Console Errors**
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getRoot')
    at t.revealLeaf (app.js:1:1638261)
    at FullCalendarPlugin.eval (plugin:obsidian-full-calendar:53889:26)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-full-calendar:53:24)
t.revealLeaf @ app.js:1
eval @ plugin:obsidian-full-calendar:53889
fulfilled @ plugin:obsidian-full-calendar:53
Promise.then (async)
step @ plugin:obsidian-full-calendar:65
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
activateView @ plugin:obsidian-full-calendar:53883
eval @ plugin:obsidian-full-calendar:53897

**Device info (please complete the following information):**
 - OS: Windows 10
 - Plugin Version 0.6.1

**Additional context**
- Using Obsidian v1.0.0
- Minimal theme in use but also occurs with no themes enabled

**Comment by davish** [comment]
This is an issue with new Obsidian 1.0 styling. Thanks for reporting!

**Comment by davish** [comment]
This is fixed with f60bbf7426fa229f7c204ce8567488a351c459a0 and will be released in 0.7.0.
