### ISSUE TITLE
Not all recurring events show up on the calendar.

### ISSUE THREAD

**Issue by DannyHatcher-Git** [davish/obsidian-full-calendar#166]
I seem to have hit a limit of recurring events which is frustrating.

Morning, Lunch, Dinner and then some events throughout the week are all recurring but now when I add a recurring event it doesn't show unless I remove a previous recurring event.

**Comment by DannyHatcher-Git** [comment]
I know how to get into the dev console but I am not sure what you want me to show you?

**Comment by DannyHatcher-Git** [comment]
I have done a bit of testing and it seems to work sometimes but not others with the recurring event. I can't seem to find a pattern yet.

**Comment by davish** [comment]
Since this was related to the end time not being set properly on the recurring event, I'll close this bug. Thanks for submitting and for help in debugging the root issue!
