### ISSUE TITLE
create not all day event is created as multiday events

### ISSUE THREAD

**Issue by ksdavidc** [davish/obsidian-full-calendar#168]
**Describe the bug**
when I create a new event, even if I unclick all day event, it creates a multiday event. The front matter i create
**To Reproduce**
1. click calendar to create new event, add title
2. unclick all day, create event
3. the event appears with the following front matter.
---
title: test
allDay: false
startTime: 10:27
endTime: 11:28
date: 2022-12-29
endDate: 2022-12-30
---
note that endDate is wrong.
5. See error

**Expected behavior**

**Screenshots**

**Console Errors**
Go to `View->Toggle Developer Tools` and open up the JavaScript console, reproduce your bug, and copy/paste any logs you see there.

these seem unrelated

plugin:obsidian-open-link-with:761 [open-link-with] fake-el with "fake_extlink" not found
eval @ plugin:obsidian-open-link-with:761
plugin:metaedit:5266 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at OnFileModifyAutomatorManager.onFileModify (plugin:metaedit:5266:29)
onFileModify @ plugin:metaedit:5266
await in onFileModify (async)
eval @ plugin:metaedit:5239
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
t.onChange @ app.js:1
e.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
m @ app.js:1
e.reconcileFileCreation @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
m @ app.js:1
e.reconcileFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
m @ app.js:1
e.reconcileFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
m @ app.js:1
e.reconcileInternalFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
m @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
Promise.then (async)
e.queue @ app.js:1
e.write @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
m @ app.js:1
t.modify @ app.js:1
eval @ plugin:obsidian-full-calendar:52484
fulfilled @ plugin:obsidian-full-calendar:53
Promise.then (async)
step @ plugin:obsidian-full-calendar:65
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
modifyFrontmatter @ plugin:obsidian-full-calendar:52452
eval @ plugin:obsidian-full-calendar:52619
fulfilled @ plugin:obsidian-full-calendar:53
Promise.then (async)
step @ plugin:obsidian-full-calendar:65
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
create @ plugin:obsidian-full-calendar:52613
eval @ plugin:obsidian-full-calendar:52809
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
submit @ plugin:obsidian-full-calendar:52797
eval @ plugin:obsidian-full-calendar:52214
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
handleSubmit @ plugin:obsidian-full-calendar:52212
callCallback2 @ plugin:obsidian-full-calendar:10928
invokeGuardedCallbackDev @ plugin:obsidian-full-calendar:10953
invokeGuardedCallback @ plugin:obsidian-full-calendar:10987
invokeGuardedCallbackAndCatchFirstError @ plugin:obsidian-full-calendar:10990
executeDispatch @ plugin:obsidian-full-calendar:13613
processDispatchQueueItemsInOrder @ plugin:obsidian-full-calendar:13633
processDispatchQueue @ plugin:obsidian-full-calendar:13642
dispatchEventsForPlugins @ plugin:obsidian-full-calendar:13650
eval @ plugin:obsidian-full-calendar:13774
batchedEventUpdates$1 @ plugin:obsidian-full-calendar:23298
batchedEventUpdates @ plugin:obsidian-full-calendar:10808
dispatchEventForPluginEventSystem @ plugin:obsidian-full-calendar:13773
attemptToDispatchEvent @ plugin:obsidian-full-calendar:12322
dispatchEvent @ plugin:obsidian-full-calendar:12277
unstable_runWithPriority @ plugin:obsidian-full-calendar:7603
runWithPriority$1 @ plugin:obsidian-full-calendar:15725
discreteUpdates$1 @ plugin:obsidian-full-calendar:23312
discreteUpdates @ plugin:obsidian-full-calendar:10818
dispatchDiscreteEvent @ plugin:obsidian-full-calendar:12258
plugin:obsidian-quiet-outline:1003 leaf-changed

**Device info (please complete the following information):**
 - osx monterey
 - Plugin Version [`0.6.1`]
 - version 1.03 of obsidian

**Additional context**

**Comment by davish** [comment]
duplicates #55
