### ISSUE TITLE
Monthly View (Set as default)

### ISSUE THREAD

**Issue by valiantgenomics** [davish/obsidian-full-calendar#170]
First of all, I want to thank you from the bottom of my heart for developing such an outstanding plugin!

My humble request is very simple. Every time I open the calendar, it defaults to the weekly-view format. I never liked the weekly-view on any calendar, be it google, calendly, etc.

I would like it so every time I open the calendar, it just defaults to the monthly view.

Of course, if someone else doesn't like that idea, they can keep the weekly-view as the default opening. That's why my humble request would be to add some sort of a toggle option where you can choose your default opening layout.

Either -monthly, -weekly, or maybe even daily. This way every time you open your calendar, you're immediately greeted with the format you like the most and you don't have to switch it manually every time.

Again, many many thanks for your hard work. I genuinely appreciate you!

**Comment by davish** [comment]
Thanks for the kind words @valiantgenomics! This feature is already covered by issue #124 and there's already a pull request (#149) that adds this functionality. I'll try to get it merged in soon.

Cheers!

**Comment by valiantgenomics** [comment]
Ah, it seems like I've missed that, my apologies for repeating the issue. Thanks for taking the time to point it out! 

You're truly awesome!
