### ISSUE TITLE
Names and Numbers of Days - Remove Underline

### ISSUE THREAD

**Issue by valiantgenomics** [davish/obsidian-full-calendar#171]
Again, I can't express how valuable this plugin is. 

I was just wondering, is there any particular reason why the dates and weekday names are underlined?

![image](https://user-images.githubusercontent.com/111633318/200208100-fd5fe1b6-bac4-4675-9446-6ff07f1dde0a.png)

In my humble opinion, it makes the dates slightly less legible at a glance. And would be awesome if this is a toggle-able option.

For example, 7 looks a bit like the letter Z when it's underlined.

I haven't seen a calendar thus far with underlined names and dates. Which is what confuses me a bit.

Anyway, I don't want this to come across as nit-picky at all. The Full Calendar plugin is sensational.

**Comment by davish** [comment]
Thanks for the suggestion @valiantgenomics! I agree that the underlining is strange. I just changed this and it will land in the next release.

**Comment by valiantgenomics** [comment]
Awesome! Thanks a lot for the consideration!
