### ISSUE TITLE
Allow "Creat note" feature in CalDav Calendar like local

### ISSUE THREAD

**Issue by Ton-yi** [davish/obsidian-full-calendar#178]
I've checked https://github.com/davish/obsidian-full-calendar/issues/25#issue-1147529739 and [#135](https://github.com/davish/obsidian-full-calendar/issues/135#issue-1325116709)

Since it's hard to write data into Caldav calendar for now.
I think it's also cool that we can just read and create note and get a link to current event inside Obsidian

I would be happy to add futuer events by using other apps and write a note after events

**Comment by davish** [comment]
If you want to actually create new events and have them show up in a CalDAV calendar, then this is a dupe of #24.
If you want to link local notes to remote CalDAV events, then this is a dupe of #172.
