### ISSUE TITLE
Recursive event folder throws an error when the folder is the Vault root

### ISSUE THREAD

**Issue by zsviczian** [davish/obsidian-full-calendar#19]
It works from subfolders of the Vault.

This is my settings page:
![image](https://user-images.githubusercontent.com/14358394/154839460-f586f694-1964-4c12-b684-5e8f4c1799e4.png)

This is the data.json generated by the plugin:
```json
{
  "calendarSources": [
    {
      "type": "local",
      "directory": "/",
      "color": null
    }
  ],
  "defaultCalendar": 0,
  "recursiveLocal": true,
  "eventsDirectory": "/"
}
```

When I changed this, removing the "/" for the root folder, the error was resolved and the calendar opened correctly.
Are you using Obsidian `normlizePath`? 
```json
{
  "calendarSources": [
    {
      "type": "local",
      "directory": "",
      "color": null
    }
  ],
  "defaultCalendar": 0,
  "recursiveLocal": true,
  "eventsDirectory": ""
}
```

![image](https://user-images.githubusercontent.com/14358394/154839691-b2a1a897-2098-4381-ad11-9f68893a0b35.png)

**Comment by zsviczian** [comment]
My mistake. The above solution did help bring up the calendar, but it did not work properly.
Also if I set a folder and set a recursive event folder, full-calendar throws the same error.

**Comment by zsviczian** [comment]
after further testing, the issue is not with the folder setting, but the `recursive event folder` setting.

**Comment by zsviczian** [comment]
Sorry for spamming you...
I am reading your code. Why are you doing a recursive folder search. You could simply filter on path like this.

```javascript
const files = calendarSource.directory === "/"
  ? app.vault.getFiles()
  : app.vault.getFiles().filter(f=>f.path.startsWith(calendarSource.directory));
```

**Comment by davish** [comment]
Hi @zsviczian, sorry for the delay on following up to this bug report. I can't reproduce this locally -- setting my calendar root to `/` and turning on recursive resolution finds all the events in my vault. Looking at the error you got, it seems like it's related to trying to render an event with incomplete frontmatter. That is a bug that I need to fix -- right now I'm casting the result from the metadata cache to the `EventFrontmatter` type I use throughout the code. That's a faulty assumption, and I should be validating my input. I'll open a ticket to track that bug.

**Comment by davish** [comment]
@zsviczian the commit referenced above should have fixed this specific error. Please let me know if you can replicate with relese `0.3.4` or above. Thank you!

**Comment by zsviczian** [comment]
Thanks. The issue is resolved.
