### ISSUE TITLE
Option to open multiple views

### ISSUE THREAD

**Issue by feedhopper** [davish/obsidian-full-calendar#194]
I would very much like to open more than one view of Full Calendar. Why?

Because I like to have the "list" variant directly underneath  my calendar (the other, small one).
Switching to week or month view inside this narrow note window makes no sense. I would rather like to have these views open i some other note tab.

**Comment by feedhopper** [comment]
I just foud out that "split right" function duplicates the calendar window.
Ater that, it's possible to switch the two calendar notes to individual views

**Comment by davish** [comment]
Closing this issue as a solution was found.
