### ISSUE TITLE
Illogical Box Size Discrepancy

### ISSUE THREAD

**Issue by valiantgenomics** [davish/obsidian-full-calendar#199]
I always preface the bug reports with how outstanding this plugin is because it's important to keep things in the right perspective. Yes, there are a few bugs here and there, but this plugin is so invaluable that it doesn't matter. So thank you for your continuous dedication to keep it up to date!

╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌

This specific bug is somewhat simple to explain. 

**The calendar boxes change size rather illogically/chaotically in the monthly view based on the number of events per box.**

For example, I'm adding only 2-3 tasks per day and the box expands by 40-50% when there's clearly a lot of space left and there's no need for the box to expand. I'd understand if I'm adding 5-10 events in one box, but that's not the case. The 2-3 events barely cover half of the box, so I don't see why it should expand and throw off the entire monthly layout.

And not only that, but when the target box expands, the entire row expands, and consequently, some of the rows above and below get compressed. But weirdly, those compressed rows also have 2-3 events in them? Which is why I've labelled this "illogical" because it doesn't make sense.

Here's a screenshot of what's happening. I'm only showing the free space for privacy reasons, but on each sides of this screenshot there are events which are causing the layout shift. You can see that box (1) is normal size, whereas box (2) is the compressed one and box (3) is the enlarged one.

![image](https://user-images.githubusercontent.com/111633318/204213828-1d413cd1-5b35-4458-9221-bb8f22761be8.png)

It would be awesome if the sizing can remain a bit more consistent. 

**For example, I don't see a reason why 4 events can't fit freely per box without expanding the box. There's enough space for all of them. Or maybe just expand it a tiny bit, like 10%? That would be perfect, since it won't throw off the layout of the monthly view.**

Just throwing some ideas out there, of course, I don't know how difficult the implementation of this would be. So please forgive me if I'm asking for something very complex or not inline with your goals/vision.

Thanks!!!

**Comment by davish** [comment]
Hi @valiantgenomics, thanks for submitting, and as always, thank you for the kind words! I think this is an issue with the underlying view library FullCalendar, since this plugin doesn't handle rendering events directly. I will close this issue here, but please feel free to [submit an issue there](https://github.com/fullcalendar/fullcalendar/issues) if you'd like.

Cheers!

**Comment by valiantgenomics** [comment]
> Hi @valiantgenomics, thanks for submitting, and as always, thank you for the kind words! I think this is an issue with the underlying view library FullCalendar, since this plugin doesn't handle rendering events directly. I will close this issue here, but please feel free to [submit an issue there](https://github.com/fullcalendar/fullcalendar/issues) if you'd like.
> 
> Cheers!

Hey! Just updated to the newest version of the Full Calendar, and I'm not sure if you fixed the box size discrepancy issue I was stating above, or the fix was inherited from the fullcalendar git directly, but the new version is brilliant!

The **+n more** link that appears if you have more than 2 events per day, which then shows you all of them upon clicking, is the perfect solution!

It really standardises the box size and keeps the monthly view neat and organised. Plus, you can add as many events as you want to a given day without completely and utterly distorting the calendar.

Just awesome! Thanks a ton!

**Comment by davish** [comment]
@valiantgenomics, thanks as always for the kind words. The thanks in this case is best directed towards @Arkadipta, who submitted this fix in PR #314. Cheers!
