### ISSUE TITLE
iCloud Calendar Sync

### ISSUE THREAD

**Issue by oak86** [davish/obsidian-full-calendar#2]
I'd love if we could get iCloud Calendar sync.

Any chance of that happening?

**Comment by davish** [comment]
One-way, readonly sync and event import from iCal into Full Calendar should be possible pretty trivial based on [Full Calendar's built in support](https://fullcalendar.io/docs/icalendar). I will have to do more research on two-way sync, see #1 for a similar discussion for GCal.

**Comment by billpetro** [comment]
I too +1 on iCal Calendar sync.

**Comment by Hileotech** [comment]
+1 on iCal for me too... don't want to do the "iCal->GCal->Obsidian-sync" procedure...
BTW it's not that important to me the two way sync, so a read-only feaure in short time is much better than a read-write approach in (much?) more time. Anyway thanks for your work!!!

**Comment by davish** [comment]
Hi all -- closing this thread in favor of #27 since I'm trying to make the Issues more atomic. Thanks!
