### ISSUE TITLE
Adding new ICS calendars is impossible in version 0.9.0

### ISSUE THREAD

**Issue by pcause** [davish/obsidian-full-calendar#206]
**Describe the bug**

In seetings I select an ics calendar.  I get the popup and pick my color.  There is then a line to enter the ics url.  I try to paste into the URL and it doesn't work.  Also can't type into the fields.

**To Reproduce**
See above

**Expected behavior**
I should be able to paste (windows ctrl+v) the URL.  If I go to a note i can pste the URL with crtl+v

**Console Errors**
none

**Device info (please complete the following information):**
Windows 11 PC

**Comment by LennardKlein** [comment]
Hey! I currently get the same bug.

**Comment by JonathanEspinosaLong** [comment]
I'm also getting this bug. I believe there should be an input box within the popup to paste the .ics url. I noticed this input was present in [this ](https://youtu.be/Hwp7p3Xv-8o?t=131) youtube video but it seems to be missing in the version I have installed (v0.9.0). As mentioned in the original issue

**Comment by davish** [comment]
Hi all, this is fixed in `0.9.1`, which should be available now. Thanks for your patience!
