### ISSUE TITLE
Add support for Tasks plugin for inline task events

### ISSUE THREAD

**Issue by pcause** [davish/obsidian-full-calendar#207]
Love the new daily notes support.  Many of us use the tasks plugin and its format for events.  Adding support for that would be great.  Using their due and recurring formats and then your time formats would be perfect for a lot of users.  The tasks plugin is one of the most popular plugins with 225K downloads.

**Comment by davish** [comment]
Thanks for submitting this issue! Integration with the tasks plugin (https://github.com/obsidian-tasks-group/obsidian-tasks) is definitely on the roadmap.

**Comment by davish** [comment]
Duplicates #219, which has some more activity on it.
