### ISSUE TITLE
Recurring events fail silently with daily note calendars

### ISSUE THREAD

**Issue by pcause** [davish/obsidian-full-calendar#208]
**Describe the bug**
I have set full calendar to use daily notes.  In full calendar I create a recurring tasks or event and neither is added.

**To Reproduce**
have a daily note calendar.
on whichever day is today click a time slot.
enter a title and then check the recur box.  select the current day of the week and the next 3 days.
can be either an event or task
click save.
nothing is created

**Expected behavior**
events appear on the calendar for today and the next 3 days.
an items is added to the specified section for events in today's daily note 

**Console Errors**
Uncaught (in promise) Error: MiniSearch: cannot remove document with ID DONE.md: it is not in the index
    at CF.remove (plugin:omnisearch:6:12068)
    at e0.removeFromMinisearch (plugin:omnisearch:39:6419)
    at jE (plugin:omnisearch:53:7235)
    at async eval (plugin:omnisearch:53:5493)
plugin:obsidian-full-calendar:9105 The specified value "hsl(214, 100%, calc(85% - 3.8%))" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
set @ plugin:obsidian-full-calendar:9105
3plugin:obsidian-full-calendar:56904 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at IcsSource.eval (plugin:obsidian-full-calendar:56904:15)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-full-calendar:78:61)
    at new Promise (<anonymous>)
    at __async (plugin:obsidian-full-calendar:62:10)
    at IcsSource.toApi (plugin:obsidian-full-calendar:56902:12)
    at eval (plugin:obsidian-full-calendar:57940:138)
    at Array.map (<anonymous>)
    at CalendarView.eval (plugin:obsidian-full-calendar:57940:123)
    at Generator.next (<anonymous>).

**Device info (please complete the following information):**
 windows 11, latest version

**Comment by davish** [comment]
Hi @pcause, recurring events are not yet supported in daily notes. Trying to add one should throw up a notice for users rather than failing silently, though.

**Comment by Kullenej** [comment]
Hello @davish. Thank you for a wonderful plugin! I wonder whether this will be implemented in the plugin or not? I might change workflow if this is not implemented before the year starts properly.

**Comment by pcause** [comment]
this is an area where using some of the tasks plugin format might make sense.  In daily notes if you use the tasks plugin format they have a recurs spec using [rrule](https://jakubroztocil.github.io/rrule/) to parse and then a start date and a due date.  You might make it appear:

- with start and no due, every instance forever or until completed
- with due and no start, every day from the date of the daily note page where it appears until due date or completed
- with start and due, every day between start and due until due or completed
- with neither start nor due, start on the date of the daily note where it appears, goes until completed.
