### ISSUE TITLE
'Calendar' app problem

### ISSUE THREAD

**Issue by menagerie198** [davish/obsidian-full-calendar#215]
**Describe the bug**
clicking on a past date (that already has a created document) in Liam's 'Calendar' produces a 'note does not exist. Do you want to create it'. error message.

Disabling 'Full Calendar' restores expected function (clicking on 30 Nov opens '2022-11-30'). 

Rolling back to v0.8.0 also resolved the issue.

This issue began with v0.9.0 of Full Calendar

**Device info (please complete the following information):**
 - OS: Win 10
 - Plugin Version 0.9.0

**Comment by davish** [comment]
Hi @menagerie198, I'm not able to reproduce this with the Daily Notes or Period Notes plugin. Could you see if there are any errors in your console? (see [here](https://forum.obsidian.md/t/how-to-access-the-console/16703) for how to open your console)

Additionally, could you attach a screenshot for the error message? That message looks like there should be an option to create a note.

Thank you!

**Comment by menagerie198** [comment]
Apologies, I have been away from my pooter for a couple of days. 
I am now running v 0.9.1 of FC, and all is well again.
