### ISSUE TITLE
Can't add past events via daily note

### ISSUE THREAD

**Issue by oldjove** [davish/obsidian-full-calendar#220]
**Describe the bug**
Using the daily note calendar, adding events in the future by typing them into the daily note works fine. However, if the event began in the past, it does not show up.

**To Reproduce**
1. Type event into daily note in which [startTime:: ] is in the past.
2. Event does not appear in calendar.

**Expected behavior**
Events should appear in calendar regardless of being in the past or the future.

**Device info (please complete the following information):**
- Windows 10
- 0.9.1

**Comment by davish** [comment]
Hi @oldjove, can you give me an example of a full line where the event did appear, and an example of a line with the event did not appear?

**Comment by davish** [comment]
This potentially seems related to #215.

**Comment by oldjove** [comment]
@davish Hmm, I'm trying it on my laptop at home this time (last time was on my office desktop) and it's working fine. Looks like it might be something specific to my setup.
