### ISSUE TITLE
Rescheduling event (stored in Daily Note) causes error message of 'recurring events in daily notes not supported' 

### ISSUE THREAD

**Issue by drannex42** [davish/obsidian-full-calendar#227]
**Describe the bug**
Rescheduling an event from inside FC using the Daily Notes format causes an error followed by a message saying recurring events in daily notes are unsupported. 

**To Reproduce**
1. Create an Event (into daily note) from within FC. 
2. Click on Event inside of FC
3. New Date, Save. 
4. Error saying unsupported for recurring event, not a recurring event.

**Comment by davish** [comment]
@drannex42 sorry for the delay on this one. I was able to reproduce it in my own calendar. I will work on a fix, but for now, dragging events around will work.
