### ISSUE TITLE
Can't add events to an iCloud calendar

### ISSUE THREAD

**Issue by maelniv** [davish/obsidian-full-calendar#232]
**Describe the bug**
I can't add events to an iCloud calendar.

**Context**
I have an iCloud calendar with several calendars inside.
![image](https://user-images.githubusercontent.com/85111445/208268973-d4e94e1d-bef6-4063-b969-b5c3ba93ad4e.png)

**To Reproduce**
1. Go to Open Full Calendar
2. Select `iCloud `to connect 
3. Log in
4. Select a time slot in the calendar
5. `Add Title` and then `Save Event`
6. See the error

**Expected behavior**
Be able to add events to my iCloud calendar from Obsidian

**Console Errors**
Nothing seems to be logged in the console, however an error appears on the screen:
![image](https://user-images.githubusercontent.com/85111445/208269196-ff994003-e3dc-462e-bea4-f7a8cf793c83.png)

**Device info (please complete the following information):**
 - OS: [ Windows 11 ]
 - Plugin Version [`0.9.1`]

**Additional context**
The selection element looks strange, as if it were empty :
![image](https://user-images.githubusercontent.com/85111445/208269282-62ca801a-4b70-43da-ab77-97fcaa9835ed.png)

And indeed, there is nothing in the select:
![image](https://user-images.githubusercontent.com/85111445/208269311-b28ca52f-cb02-458d-90a4-139beaf36932.png)

**Comment by ok-blip** [comment]
I also get the same issues and I'm unable to create any further events

When I try I get the message: "Cannot read properties of undefined (reading 'type')"

**Comment by jebeaudoin** [comment]
Is this new? I thought you could only add and edit local calendars?

**Comment by davish** [comment]
iCloud calendars are read-only. See #135 for more discussion on this. If you would like to add events with the plugin, please add a Full Note or Daily Note calendar.
