### ISSUE TITLE
0.9.4 does not load on latest Mobile release

### ISSUE THREAD

**Issue by davebhc71** [davish/obsidian-full-calendar#236]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console Errors**
Go to `View->Toggle Developer Tools` and open up the JavaScript console, reproduce your bug, and copy/paste any logs you see there.

**Device info (please complete the following information):**
 - Plugin Version [e.g. `0.1.3`]

**Additional context**
Title says it all!

**Comment by davish** [comment]
Hi @davebhc71, please fill out the template. I can’t help reproduce the issue with just a title. 

My guess is that I updated the required version of Obsidian to 1.1.1, which has not yet been released on mobile. I can try rolling it back to 0.16 and see if that makes a difference, but without knowing the exact error message I can’t do much.
