### ISSUE TITLE
Allowing Time to be included in creation of new notes

### ISSUE THREAD

**Issue by GeneticallyModifiedAlex** [davish/obsidian-full-calendar#237]
A toggleable setting that allows the user to have appointments timestamped as well as date stamped. This way, you can have non-recurring events that have the same name. i.e. If I want to put multiple events Called ''Break'' on the Same Day.

**Comment by davish** [comment]
This is one way to help make #12 less of an issue.

**Comment by davish** [comment]
Closing this issue since this suggestion is mentioned in #12
