### ISSUE TITLE
[Feature request]Add an option that no adding date numbers to original filenames

### ISSUE THREAD

**Issue by Rsose** [davish/obsidian-full-calendar#251]
## Delete this before submitting
Please include only one feature request per Issue. You can submit as many Issues as you have ideas. Thank you!
Hi Davish
I have some problems because I need the file name to remain the same. Don't add date numbers to the prefix of the file name even when dragging tasks in the full calendar 
I also am working with other database plugins, but once there are adding date numbers, the file title will become very long and very inconvenient
In this case, I have to delete the date number every time, which is very troublesome 
**After adding dragging it will be added date numbers**
![image](https://user-images.githubusercontent.com/51273534/211858207-b9f0a1a0-af01-4735-8b90-fa70106a4afd.png)
**No problem showing in Full calendar**
![image](https://user-images.githubusercontent.com/51273534/211858296-f1f870c2-6611-4eab-b725-78e9030bab5f.png)

My suggestion is can you add an option in the settings to set date numbers adding them or not,my main requirement is not to automatically add the date to the filename

Thanks
Waiting for a reply

**Comment by davish** [comment]
Without having the date in the filename, a title for an event will be globally unique, so that no other event in that calendar could have the same name. This is pretty limiting, so I don't intend on adding an option to remove the date from the filename.
