### ISSUE TITLE
Calendar not rendering

### ISSUE THREAD

**Issue by Educorreia932** [davish/obsidian-full-calendar#258]
**Describe the bug**

After trying to open the calendar, I'm met with an empty view.

**Screenshots**

![image](https://user-images.githubusercontent.com/44172778/213414687-b8a7ad24-7366-46e1-aef2-a6ee81a40763.png)

**Console Errors**

![image](https://user-images.githubusercontent.com/44172778/213414758-37a29654-4615-4638-b368-143f655b2e5c.png)

**Device info (please complete the following information):**
 - OS: Windows 
 - Plugin Version 0.9.5
 - Obsidian Version 1.1.9

**Comment by davish** [comment]
Hi @Educorreia932, what other plugins do you have installed?

**Comment by Educorreia932** [comment]
> Hi @Educorreia932, what other plugins do you have installed?

![image](https://user-images.githubusercontent.com/44172778/214762044-3d446a03-7697-4951-b9a3-a0454f2d0917.png)
![image](https://user-images.githubusercontent.com/44172778/214762067-d438c69a-ca3b-488b-9aa7-d27c6abf0fa0.png)

The ones in the pictures were the ones I had installed, but after a reload of the plugins it started working again.
