### ISSUE TITLE
end date is not showing in the calendar

### ISSUE THREAD

**Issue by AppleElephants** [davish/obsidian-full-calendar#263]
I dont it is bug or not

when I make event, for example, from 1st November to 10th, it just showing from 1st November to 9th with color.

can you help me out?

<img width="788" alt="Screenshot 2023-01-30 173831" src="https://user-images.githubusercontent.com/123480707/215428213-2f0d4a13-2b32-4cf1-add3-0843a3db27a0.png">
<img width="314" alt="Screenshot 2023-01-30 173959" src="https://user-images.githubusercontent.com/123480707/215428219-aee63451-406e-40da-bb1a-d20c43f7b2ff.png">

**Comment by davish** [comment]
This is working as intended. The end date is 1 more than the actual end of the event.

**Comment by davish** [comment]
See #259
