### ISSUE TITLE
Calendar not showing

### ISSUE THREAD

**Issue by b-lca** [davish/obsidian-full-calendar#264]
Before it was working perfectly for me I have no Idea what caused the issue.

![image](https://user-images.githubusercontent.com/71517739/215531533-20249115-10ac-430d-9850-de43fb3a6816.png)

The plugins I have installed:
![image](https://user-images.githubusercontent.com/71517739/215536447-01409b5e-0133-4787-a249-59b5ce126cac.png)
![image](https://user-images.githubusercontent.com/71517739/215536749-fbf8c8dd-9032-4857-a56f-f4caefcafd15.png)

**Comment by davish** [comment]
I'm sorry, I don't think I'll be able to debug this considering the number of plugins installed. I'd recommend https://github.com/chrisgrieser/obsidian-divide-and-conquer to help debug.
