### ISSUE TITLE
Workspaces don't save the sidebar settings correctly

### ISSUE THREAD

**Issue by DannyHatcher-Git** [davish/obsidian-full-calendar#265]
**Describe the bug**
When saving the sidebar in a workspace, reactivating the workspace changes the sidebar full calendar to the full calenar dragged in option.

**To Reproduce**
Save the sidebar full calendar in a workspace (I use workspace plus)
Activate the workspace
Look at the full calendar sidebar.

**Expected behavior**
Sidebar setting to be saved.

**Device info (please complete the following information):**
 - Windows
 - Plugin Version 0.9.5

**Comment by Arkadipta** [comment]
Possibly related, the calendar in sidebar reverts to default desktop view upon closing and reopening obsidian.

**Comment by Smitty010** [comment]
+1

**Comment by davish** [comment]
This should be fixed by #286, which just was merged in! I'll cut a new release soon.
