### ISSUE TITLE
Mobile Initial View setting reverts to previous value when Obsidian restarted

### ISSUE THREAD

**Issue by Smitty010** [davish/obsidian-full-calendar#267]
**Describe the bug**
If I go into the settings and change the Mobile Initial View, the value isn't saved.  There is no save button.  Restarting Obsidian reverts the value to what it was before the setting.

**To Reproduce**
1. Go into Full Calendar settings
2. Change the value of Mobile Initial View to something else
3. Restart Obsidian
4. Check the value of Mobile Initial View

**Expected behavior**
The value should be saved so that the new value is there when Obsidian is restarted.

**Screenshots**
So, we are talking about the same thing: 
![image](https://user-images.githubusercontent.com/3760075/216481896-84dcc285-5e9b-41ab-9568-62d9d982fedf.png)

**Console Errors**
There were no console errors

**Device info (please complete the following information):**
- Windows 11
- Obsidian 1.1.12
- Full Calendar 0.9.5

**Additional context**

**Comment by davish** [comment]
Fixed by #285.
