### ISSUE TITLE
Linked calendar event should be editable

### ISSUE THREAD

**Issue by vovech** [davish/obsidian-full-calendar#269]
Hello, I would like to suggest the next feature. 

When you edit a linked event (.ics and others) by default, you cannot edit it. Because of course there is no way to edit third party calendars due to API constraints. But instead, what you want to do is to have an ability to write down notes on this event locally. Otherwise, you have to do it in a different not and cannot link it with an event.

What should be happened:
  - When you edit a linked event, a new not is created on the same destination folder as local events.
  - Linked note to event may have a prefix or meta key with "linked calendar" value.
  - If a linked calendar event is removed, the linked note is still persisted. 

Thanks in advance.

**Comment by FelixBrakel** [comment]
I have an alternative proposal. It may not be possible to edit linked calendars but you could export your local Obsidian calendar to an ics file (which the FullCalendar JS library supports I think). 

Getting the ics file into Google Calendar (or whatever you use) and getting it to update is another matter but definitely something you can DIY. You should be able to set up something like Google Drive to host the file if you want to go for the easy way, although the calendar will probably update pretty slowly.

Really as long as you have an ics file you can self-host the calendar pretty easily with like a raspberry pi.

**Comment by vovech** [comment]
@FelixBrakel I don't need to export it. I want to use FullCalendar in Obsidian but to be able to edit events that are comming from a calendar such as google calendar. I want to create notes out of linked events, which I'm not able right now.

**Comment by davish** [comment]
This request would be fulfilled either by #40 or #25, both of which are highly requested features that are on the roadmap.
