### ISSUE TITLE
Calendar is really narrow?

### ISSUE THREAD

**Issue by ReaderGuy42** [davish/obsidian-full-calendar#275]
**Describe the bug**
The calendar is showing up but is really narrow. It takes up maybe a third of the note leaf.
**To Reproduce**
Install plugin
open plugin
see that it's narrow

**Expected behavior**
the calendar should take up more space or the whole leaf?

**Screenshots**
![image](https://user-images.githubusercontent.com/71895400/217918908-afb34902-1c30-4b83-8074-98c48aea8eaa.png)

**Console Errors**
![image](https://user-images.githubusercontent.com/71895400/217919085-d6b2f817-d9be-41bd-bab0-ca1c8ed0c16b.png)

**Device info (please complete the following information):**
 - OS: Linux Mint
 - Plugin Version: 0.9.5

**Additional context**
It works in the Sandbox Vault, but not in my actual vault. Can't figure out why though.

**Comment by ExtremelyHugeTires** [comment]
Do you have some CSS enabled for aligning columns from the Dataview plugin?

**Comment by ReaderGuy42** [comment]
Yes, I did. Thank you! I had a snippet that aligns tables to the left. Disabling that solved the problem :)
