### ISSUE TITLE
Store multiple events within a single note

### ISSUE THREAD

**Issue by davish** [davish/obsidian-full-calendar#28]
>I would also love for some functionality of scraping event information *from* the daily notes! Of course it wouldn't have the full amount of capabilities of a full event page, (dragging and dropping would probably be a pain to enable) but being able to quickly add an event name, start and end time within for a day would be amazing.

_Originally posted by @wychwitch in https://github.com/davish/obsidian-full-calendar/issues/6#issuecomment-1045033205_

You could specify as much event info as you want using inline dataview fields, and the plugin would "fill in the blanks" using the page's frontmatter. So you could have a page with `fullCalendar_date: 2022-02-22`, and then bullet points with `[startTime:: 5:00pm] [endTime:: 7:15pm]` would be able to be populated on the calendar.

You would be able to edit any field specified in-line from the calendar as well. But page-wide fields would be locked. To move an event to a different date in this example, you would have to manually move it to a different note.

Relying on custom frontmatter means that you could easily integrate this with your daily note / periodic note templates, but you're not locked into those formats.

**Comment by wychwitch** [comment]
Yessss this sounds perfect!!! Exactly the functionality i had in mind

**Comment by yanly007** [comment]
I think it would be nice if we can use this along with the manual adding of events directly in calendar since its much faster.
events added to the same day from calendar are added to the note for that particular day

**Comment by davish** [comment]
@yanly007 when inline notes are added I'll make sure to add a setting to create new notes within a daily note.

**Comment by pcause** [comment]
i'd posted on another thread about the style that the itinerary plugin uses.  that one uses full0-calendar for display as well.  you can see how they gather events from files and how they allow event specification.  if you want events in the yaml front matter, could you perhaps make the event spec an array of events?  that way you can use the same UI and the like,  but you pull multiple from a note and when someone edits, you find that event in the array.  should be less code change than using events in the body of notes.
