### ISSUE TITLE
Add Day List view in sidebar

### ISSUE THREAD

**Issue by igelbox** [davish/obsidian-full-calendar#287]
Having Week List view is great unless you have lotsa events per week, e.g. you tracking some regular events using calendar:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/5264687/219972459-516f9625-b08a-4bce-ab12-e31e8eb29000.png">
in this case you have to scroll to the bottom almost every time you opening the sidebar.

# Proposal
It seems the FullCalendar component supports `listDay` view as well as the current `listView` so it could be added easily:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/5264687/219972999-59d1c1db-0bea-401d-8816-6dd922e4474a.png">

# Concerns
This makes `Next Day` button almost invisible. So probably this one should be implemented after #48.

**Comment by davish** [comment]
I will close this as a subset of #48. Thank you for submitting!
