### ISSUE TITLE
Question & discussion on feature: How to see remote calendar events in future months

### ISSUE THREAD

**Issue by TangdizhiH** [davish/obsidian-full-calendar#299]
First of all, thank you davish for making this magnificent plugin to make event management inside obsidian possible. This plugin really makes my life easily with obsidian as I no longer need to open up the browser to see what event do I have

I would like to ask the loading of remote calendars ( CalDAV more specifically). I have my Nextcloud instance and I've connected all my calendars into full calendar. But the thing is that I can't really see the future events (e.g. in 2 months) from full calendar when I open it. I usually need to wait for sometimes in order to load events. 

I also notice that the loading of remote calendar is much slower and I don't have any **visual hint if the my remote calendars are loaded or failed**. Without visual hint, I could well doubt that if I really don't have a event at the desired time slot or is it just not appearing. So sometimes I do have to either wait a bit to make sure my calendar is loaded 2) or open up the website to check the time slot there.

I know that dealing with the remote calendar is much difficult dependent on the network issue or other factors. But I would like to ask if it is possible to 1. have a visual hint on calendar UI about the availability of remote Calendars 2. to have a local copy of remote calendars such that the loading can be faster?  3. or to expose an option at setting to specify how many future month/day events do you want to load in advance (but this is potential bad for those who opens obsidian just to check their events.)

I think the above three are possible methods to deal with the scenario I mentioned. I would like to know how you deal with this problem.

Thanks for your great work and hope you a good day.

**Comment by davish** [comment]
Hi @TangdizhiH, thank you for the kind words! All these requests are coming quite soon. The experience with remote ICS and CalDAV calendars will be improved upon in the next update, you can track #303 for progress on that. Remote calendars will be cached after they're accessed the first time, and refreshed from time to time. If any calendar fails to refresh, there will be a Notice in the top-right corner of the window. I'll close this issue as being related to #77, but know that your feedback is appreciated and it will be addressed soon!
