### ISSUE TITLE
Folders named in upper case cannot be resolved

### ISSUE THREAD

**Issue by windily-cloud** [davish/obsidian-full-calendar#3]
![image](https://user-images.githubusercontent.com/30640638/154318857-4165dfc2-4c9e-4fec-b7cb-9fc45f880cd1.png)
I guess it's a problem here.

**Comment by StefanoRausch** [comment]
Same here does not recognise my folders' names if they are not in small letters.

By the way: Looks good for a first beta!

**Comment by davish** [comment]
Thanks for tracking down this bug, @windily-cloud! Luckily it was a quick fix and it'll be included in the next release.

**Comment by davish** [comment]
This has been released in `0.1.1`

**Comment by windily-cloud** [comment]
Thanks for your efforts, this plugin is really wonderful!👍👍👍
