### ISSUE TITLE
Keep row height consistent in month view with (+x more) for overflow events

### ISSUE THREAD

**Issue by Arkadipta** [davish/obsidian-full-calendar#300]
**Describe the bug**
In the month view of full-calendar, the row height constantly increases on adding new event. 

**To Reproduce**
1. Create a bunch of events on the same day in full-calendar
2. Change the view to month-view

**Expected behavior**
Instead of changing the row height to accommodate more events, the row heights should be fixed. Extra events will be hidden with a message (+X more). See [https://fullcalendar.io/demos](https://fullcalendar.io/demos).

**Screenshots**
Presently: 
![FC-comp1](https://user-images.githubusercontent.com/33596564/222122152-ca921b88-3f12-4241-8da4-b617cf017238.jpg)

Expected:
![FC-comp2](https://user-images.githubusercontent.com/33596564/222122199-63802c0b-e71f-4f47-b251-fddc0cf7fdaa.jpg)

**Device info (please complete the following information):**
 - OS: Linux (Flatpak)
 - Plugin Version: 0.9.5

Thanks a lot for the plugin.

**Comment by davish** [comment]
Changing this from a bug to an enhancement, since this isn't actually inhibiting the ability to use the plugin.
