### ISSUE TITLE
Support synchronizing OSX Calendar.app calendars from local sqlite database

### ISSUE THREAD

**Issue by castelln** [davish/obsidian-full-calendar#304]
As of OSX Ventura, calendar events for certain types of Calendar.app accounts (in my case, Exchange-synced) are stored in a local sqlite database (found in `~/Library/Calendars/$CALENDAR_NAME.sqlitedb`). 

As a plugin user, I would like to be able to sync events in my local calendar to Full Calendar within Obsidian, so that I can create meeting notes, populate my calendar, and generally take advantage of this wonderful plugin.

While making the sync two-way - allowing the user to edit meetings in Obsidian and seeing the changes in their local calendar - would be fantastic, I also assume that would require substantially more work. Even just a one-way sync (local -> Obsidian) would be really cool to see.

**Comment by davish** [comment]
This is an interesting idea, but I'm not particularly interested in developing OS-specific functionality as part of Full Calendar. You should be able to sync events from your Apple Calendar by following the [instructions in the documentation](https://davish.github.io/obsidian-full-calendar/calendars/caldav/).

**Comment by castelln** [comment]
It's a hosted Exchange calendar, so no support for CalDAV (or any other connection options) unfortunately. 

Thanks for taking a look at least! I may take a crack at it myself and fork or throw over a PR if/when I can figure out a way to do this.

**Comment by davish** [comment]
Ah, my mistake for assuming it was a personal Apple Calendar! Thanks for understanding 😄
