### ISSUE TITLE
Modifying an entry in Daily Note Calendar with many events in a single note froze Obsidian

### ISSUE THREAD

**Issue by kohane27** [davish/obsidian-full-calendar#306]
Hello there. Hope you're doing well. Thank you for creating and maintaining `obsidian-full-calendar`.

**Describe the bug**

Please see the following gif:

https://user-images.githubusercontent.com/57322459/224332740-d2f809f7-eb05-41a4-8258-acbc8ee33074.mp4

1. modify an entry in Daily Note Calendar
2. Obsidian is frozen and has become unresponsive to any mouse input. I had to kill Obsidian

**Expected behavior**
Obsidian doesn't freeze (i.e., becoming unresponsive)

**Console Errors**
N/A as Obsidian is frozen

**Device info (please complete the following information):**
 - OS: Linux (using flatpak `md.obsidian.Obsidian 1.1.16  stable`
 - Plugin Version `0.9.5`

**Additional context**

### What I've tried

I tried modifying multiple entries at the same time using the built-in Vim mode (block selection) and it also is frozen after editing:

https://user-images.githubusercontent.com/57322459/224332147-904c2d66-26f8-409c-a165-0f90cc5da04a.mp4

I tried modifying the entry in an external editor:

https://user-images.githubusercontent.com/57322459/224332180-a669b123-f73b-43ba-85d5-25686cc1216b.mp4

1. Scrolling in Obsidian on the left to make sure Obsidian is working
2. modify an entry in Daily Note Calendar (using Neovim)
3. Can see a flash in Obsidian and the first entry was updated
4. Go back to Obsidian and it's broken (frozen) and unresponsive to any mouse input.

I also tried removing all other components in my Daily Note such that only the below Daily Note Calendar template remains. But the same freezing issue occurs.

## With only a few entries, this freezing doesn't happen

As can be seen from the below gif:

https://user-images.githubusercontent.com/57322459/224332596-0ff76c05-5caa-4109-9b00-e75ade4a2fff.mp4

Note: if you look closely, after modifying multiple entries, Obsidian has a slight input lag (the input was unresponsive for a split second).

I suspect the issue has to do with too many entries in Daily Note Calendar, and `obsidian-full-calendar` failed to update the Daily Note Calendar. Given that with only a few entries, this freezing doesn't happen. 

However, this broke my workflow. I have the following template in my daily note so that I can easily modify as the day goes by:

```md
### Day Planner

- wake-up [startTime:: 07:00]  [endTime:: 07:15]
- XX [startTime:: 07:15]  [endTime:: 07:30]
- XX [startTime:: 07:30]  [endTime:: 07:45]
- XX [startTime:: 07:45]  [endTime:: 08:00]
- XX [startTime:: 08:00]  [endTime:: 08:15]
- XX [startTime:: 08:15]  [endTime:: 08:30]
- XX [startTime:: 08:30]  [endTime:: 08:45]
- XX [startTime:: 08:45]  [endTime:: 09:00]
- XX [startTime:: 09:00]  [endTime:: 09:15]
- XX [startTime:: 09:15]  [endTime:: 09:30]
- XX [startTime:: 09:30]  [endTime:: 09:45]
- XX [startTime:: 09:45]  [endTime:: 10:00]
- XX [startTime:: 10:00]  [endTime:: 10:15]
- XX [startTime:: 10:15]  [endTime:: 10:30]
- XX [startTime:: 10:30]  [endTime:: 10:45]
- XX [startTime:: 10:45]  [endTime:: 11:00]
- XX [startTime:: 11:00]  [endTime:: 11:15]
- XX [startTime:: 11:15]  [endTime:: 11:30]
- XX [startTime:: 11:30]  [endTime:: 11:45]
- XX [startTime:: 11:45]  [endTime:: 12:00]
- XX [startTime:: 12:00]  [endTime:: 12:15]
- XX [startTime:: 12:15]  [endTime:: 12:30]
- XX [startTime:: 12:30]  [endTime:: 12:45]
- XX [startTime:: 12:45]  [endTime:: 13:00]
- XX [startTime:: 13:00]  [endTime:: 13:15]
- XX [startTime:: 13:15]  [endTime:: 13:30]
- XX [startTime:: 13:30]  [endTime:: 13:45]
- XX [startTime:: 13:45]  [endTime:: 14:00]
- XX [startTime:: 14:00]  [endTime:: 14:15]
- XX [startTime:: 14:15]  [endTime:: 14:30]
- XX [startTime:: 14:30]  [endTime:: 14:45]
- XX [startTime:: 14:45]  [endTime:: 15:00]
- XX [startTime:: 15:00]  [endTime:: 15:15]
- XX [startTime:: 15:15]  [endTime:: 15:30]
- XX [startTime:: 15:30]  [endTime:: 15:45]
- XX [startTime:: 15:45]  [endTime:: 16:00]
- XX [startTime:: 16:00]  [endTime:: 16:15]
- XX [startTime:: 16:15]  [endTime:: 16:30]
- XX [startTime:: 16:30]  [endTime:: 16:45]
- XX [startTime:: 16:45]  [endTime:: 17:00]
- XX [startTime:: 17:00]  [endTime:: 17:15]
- XX [startTime:: 17:15]  [endTime:: 17:30]
- XX [startTime:: 17:30]  [endTime:: 17:45]
- XX [startTime:: 17:45]  [endTime:: 18:00]
- XX [startTime:: 18:00]  [endTime:: 18:15]
- XX [startTime:: 18:15]  [endTime:: 18:30]
- XX [startTime:: 18:30]  [endTime:: 18:45]
- XX [startTime:: 18:45]  [endTime:: 19:00]
- XX [startTime:: 19:00]  [endTime:: 19:15]
- XX [startTime:: 19:15]  [endTime:: 19:30]
- XX [startTime:: 19:30]  [endTime:: 19:45]
- XX [startTime:: 19:45]  [endTime:: 20:00]
- XX [startTime:: 20:00]  [endTime:: 20:15]
- XX [startTime:: 20:15]  [endTime:: 20:30]
- XX [startTime:: 20:30]  [endTime:: 20:45]
- XX [startTime:: 20:45]  [endTime:: 21:00]
- XX [startTime:: 21:00]  [endTime:: 21:15]
- XX [startTime:: 21:15]  [endTime:: 21:30]
- XX [startTime:: 21:30]  [endTime:: 21:45]
- XX [startTime:: 21:45]  [endTime:: 22:00]
- XX [startTime:: 22:00]  [endTime:: 22:15]
- XX [startTime:: 22:15]  [endTime:: 22:30]
- XX [startTime:: 22:30]  [endTime:: 22:45]
- XX [startTime:: 22:45]  [endTime:: 23:00]
- XX [startTime:: 23:00]  [endTime:: 23:15]
- XX [startTime:: 23:15]  [endTime:: 23:30]
```

## Conclusion

1. Modifying any entry, either inside Obsidian or with an external editor (like Neovim) would break Obsidian.

2. Reducing the number of entries in Daily Note Calendar and this freezing disappears.

Any input is much appreciated. Thank you.

**Comment by kohane27** [comment]
I've verified that if I use 30-min intervals, there's no freezing either with editing entries in an external editor or within Obsidian:

```md
### Day Planner

- wake-up [startTime:: 07:00]  [endTime:: 07:30]
- breakfast [startTime:: 07:30]  [endTime:: 08:00]
- breakfast [startTime:: 08:00]  [endTime:: 08:30]
- XX [startTime:: 08:30]  [endTime:: 09:00]
- XX [startTime:: 09:00]  [endTime:: 09:30]
- XX [startTime:: 09:30]  [endTime:: 10:00]
- XX [startTime:: 10:00]  [endTime:: 10:30]
- XX [startTime:: 10:30]  [endTime:: 11:00]
- XX [startTime:: 11:00]  [endTime:: 11:30]
- XX [startTime:: 11:30]  [endTime:: 12:00]
- XX [startTime:: 12:30]  [endTime:: 13:00]
- XX [startTime:: 13:30]  [endTime:: 14:00]
- XX [startTime:: 14:00]  [endTime:: 14:30]
- XX [startTime:: 14:30]  [endTime:: 15:00]
- XX [startTime:: 15:00]  [endTime:: 15:30]
- XX [startTime:: 15:30]  [endTime:: 16:00]
- XX [startTime:: 16:00]  [endTime:: 16:30]
- XX [startTime:: 16:30]  [endTime:: 17:00]
- XX [startTime:: 17:00]  [endTime:: 17:30]
- XX [startTime:: 17:30]  [endTime:: 18:00]
- XX [startTime:: 18:00]  [endTime:: 18:30]
- XX [startTime:: 18:30]  [endTime:: 19:00]
- XX [startTime:: 19:00]  [endTime:: 19:30]
- XX [startTime:: 19:30]  [endTime:: 20:00]
- XX [startTime:: 20:00]  [endTime:: 20:30]
- XX [startTime:: 20:30]  [endTime:: 21:00]
- XX [startTime:: 21:00]  [endTime:: 21:30]
- XX [startTime:: 21:30]  [endTime:: 22:00]
- XX [startTime:: 22:00]  [endTime:: 22:30]
- XX [startTime:: 22:30]  [endTime:: 23:00]
- XX [startTime:: 23:00]  [endTime:: 23:30]
```

**Comment by davish** [comment]
hey @kohane27, `0.10.0` has landed a large rewrite of the plugin. Could you see if updating fixes your issue?

**Comment by kohane27** [comment]
Hello @davish , I tried and the freezing bug is gone. I tried editing a single entry and multiple entries both within Obsidian and with an external editor. Thank you for this quick fix!

**Comment by davish** [comment]
Thank you for submitting! I'm glad the plugin's performance has improved enough to be usable for your use-case.
