### ISSUE TITLE
Some ICS calendars add event with given ID twice to the EventStore

### ISSUE THREAD

**Issue by davish** [davish/obsidian-full-calendar#309]
**Describe the bug**
When loading in an ICS calendar, the plugin gives the notification that "A remote calendar failed to load. Check the console for more details."

The console then gives the following error:
```
plugin:obsidian-full-calendar:64696 Revalidation failed with reason: Error: Event with given ID "<EVENT ID>" that was supposed to be added to calendar "ical::<CALENDAR URL>" already exists in the EventStore within calendar "<SAME CALENDAR URL>".
eval @ plugin:obsidian-full-calendar:64696
```

**Expected behavior**
Calendars are correctly imported.

**Device info (please complete the following information):**
 - OS: macOS
 - Plugin Version 0.10.3

**Additional context**
This happens when an ICS file contains two events with the same UID. I assumed from the UID spec that, well, the UID would be a unique identifier. This is not the case. Specifically, when one instance of a recurring event is modified, both the recurring event and the single instance will have the exact same UID.

**Comment by loganpaulmatheny** [comment]
Hi @davish I'm getting this bug when I try and bring in my ical. Is there anything I can do correct the behavior? 

`plugin:obsidian-full-calendar:64715 Revalidation failed with reason: Error: Event with given ID "ics::B70BA8DA-BBED-4A6B-BED7-06154F63F533::2023-04-20::single" that was supposed to be added to calendar "caldav::https://caldav.icloud.com/97956022/calendars/E28A2750-0A74-45AE-BB28-58DAA0AA99A0/" already exists in the EventStore within calendar "caldav::https://caldav.icloud.com/97956022/calendars/E28A2750-0A74-45AE-BB28-58DAA0AA99A0/".
eval @ plugin:obsidian-full-calendar:64715`
