### ISSUE TITLE
Multi-Day-Event is not shown properly

### ISSUE THREAD

**Issue by Puma-HC-Stirn** [davish/obsidian-full-calendar#319]
**Describe the bug**
Multi-Day-Event is not shown properly

**To Reproduce**
Steps to reproduce the behaviour:

Make a file with some title and
   allDay: true
   startTime: 
   endTime: 
   date: 2023-04-03
   endDate: 2023-04-03
In full-calendar, this event is shown for 2023-04-03, an All-Day-Event.

Now extend this event for another day:
   allDay: true
   startTime: 
   endTime: 
   date: 2023-04-03
   endDate: 2023-04-04
In full-calendar, this event is shown for 2023-04-03, an All-Day-Event, as before.

**Expected behavior**

The event should now cover two days, if date and endDate are on two consecutive days.

**Device info (please complete the following information):**
 - OS: [macOS 10.15.7]
 - Plugin Version [e.g. `0.10.5`]

**Comment by davish** [comment]
This is working as intended. The end date is an exclusive bound, so if you're setting it directly, you need to set the end date to be the day after the intended end date for it to show up properly on the calendar. See #259

**Comment by Grant837** [comment]
@davish I just would like to say that "The end date is an exclusive bound" is not really what the average user would be expecting - on all calendar tools I have used, the last date given for recurring events is included in the event range.  I was fooled by this too, and was going to enter it as a bug...
