### ISSUE TITLE
calendar directory can't read all subfolder file

### ISSUE THREAD

**Issue by NKid** [davish/obsidian-full-calendar#321]
**Describe the bug**
File Tree
```
MyBrain/
└── 00-Daily/
    └── 2023/
        └── 03/
            ├── 2023-03-01.md
            ├── 2023-03-15.md
            └── 2023-03-29.md
```
**2023-03-01.md content**
```
---
title: Nice Day
allDay: true
date: 2023-03-01
---

Today was a nice day.   
The sun was shining, and the temperature was just right.  
I went for a walk in the park and took in all the beautiful scenery.  
```

Choose "00-Daily" folder to add calendar (Full note)
calendar show nothing.

But choose "00-Daily/2023/03" folder to add calendar (Full note)
calendar show all notes.

**Expected behavior**
Choose "00-Daily" folder should show all subfolder file

**Device info (please complete the following information):**
 - OS: Windows 10
 - Plugin Version:  0.10.5

**Comment by davish** [comment]
The recursive files feature was removed in `0.10.0`.
