### ISSUE TITLE
Mobile Initial View?

### ISSUE THREAD

**Issue by davebhc71** [davish/obsidian-full-calendar#327]
**Describe the bug**
Does the plugin consider an iPad  a ‘mobile device’, because I can not get my iPad Air to display 3 Days in Mobile Initial View. 

**Expected behavior**
I expected to be able to take advantage of the 3 day view on an iPad.

**Device info (please complete the following information):**
 - OS: iPadOS 16.5 Beta
 - Plugin Version v0.10.6

**Comment by davish** [comment]
Mobile vs desktop is determined by the pixel width of the view, so your iPad probably has too high a resolution to display the mobile view. Customizing views has been requested in #48.
