### ISSUE TITLE
Full Calendar no longer will show notes in sub folders?

### ISSUE THREAD

**Issue by venturewise** [davish/obsidian-full-calendar#332]
After updating, I see that the option for "Recursive search through folders" had been removed. 
1. You should update the documentation at https://davish.github.io/obsidian-full-calendar/settings/sources/ so this isn't shown in the screenshot
2. You should add a line that "a calendar will only display direct child notes in a directory" or similar.

In case you were wondering what my use case was for having that feature...
I had been keeping my notes in year/month sub folders, so I'd have a max of 30 notes per month folder in order to keep it readable. Do you have any tips for me?

**Daily Incidents**
----> 2023-01
           |------>2023-01-03 Here is an incident
           |------>2023-01-05 Another incident happened
           |------>2023-01-15 Maintenance of something
----> 2023-02
           |------>2023-02-07 Feb's first incident
           |------>2023-02-07 This one was a meeting

**Comment by davish** [comment]
This feature was removed in version `0.10.0`. The reasoning is that it wasn't well supported throughout the whole create-update-delete event flow. You could read events in nested sub-folders, but changing the name or date of an event might cause the event to bubble back up to the top level, and events were always created in the top-level. Organizing sub-sets of a calendar is now possible with daily note events, as well.

**Comment by venturewise** [comment]
I didn't create the ticket to ask you to bring the feature back, I was hoping you would update the documentation to with an updated screenshot without the feature in it, and drop a line that you must have all full note events in the same directory, no nests.
