### ISSUE TITLE
Only Mobile View displayed in Sidebar

### ISSUE THREAD

**Issue by malevans** [davish/obsidian-full-calendar#333]
**Describe the bug**
When opening Full Calendar in the sidebar it only opens in Mobile view where previously it has been opening in full desktop view. This seems to change intermittently.

**Device info (please complete the following information):**
 - OS: Win11
 - Plugin Version 0.10.6

**Comment by davish** [comment]
Mobile/desktop view is determined by the width of the view in pixels. If you make the sidebar very wide, or you have a high-resolution screen, your sidebar might render the desktop view.
