### ISSUE TITLE
The Hotkey "upgrade note to event" is no longer available in 0.10.6

### ISSUE THREAD

**Issue by JISL1** [davish/obsidian-full-calendar#334]
**Describe the bug**
The key shorcut "upgrade note to event" is no longer available in 0.10.6 (MacOS version)

**To Reproduce**
Look for it in the hotkeys.

**Expected behavior**
Still having this hotkey and related feature available.

**Screenshots**
![Screenshot 2023-04-04 at 11 29 26](https://user-images.githubusercontent.com/3155077/229750516-9b6d69ea-23ae-4342-99d1-49f39de00c37.png)

**Device info (please complete the following information):**
 - OS: MacOS 13.3
 - Plugin Version [e.g. `0.10.6`]

**Additional context**
Not sure it's a bug. Could be a development choice...

**Comment by davish** [comment]
Hi @JISL1, yes, this was a development choice. The feature was removed in `0.10.0`.
