### ISSUE TITLE
The latest version of the plugin is completely buggy on the mobile version.

### ISSUE THREAD

**Issue by Akira7118** [davish/obsidian-full-calendar#335]
In the latest version, when you try to open the calendar both with commands and with the icon, not only does the calendar not open, but on some occasions, it completely crashes Obsidian, preventing access to the vault as well (iOS iPad mobile version). In addition, I have noticed that now the task checkboxes do not work correctly, making it impossible to check or uncheck a task. (lates version windows)

**Comment by davish** [comment]
@Akira7118 please submit one issue per bug and please use the bug report template. I'm closing this issue for lack of specificity.
