### ISSUE TITLE
Events Cannot Be Deleted

### ISSUE THREAD

**Issue by StefanoRausch** [davish/obsidian-full-calendar#4]
I have tried the following:

1. Opening the modal does not provide the option to delete an event.
2. Deleting the event in the "events" folder does not remove the entry in the FC view.
3. Right-click does not offer the option to delete the event. In fact, the right-click is currently not supported.

It would be fantastic if you could implement all three options.

**Comment by davish** [comment]
I've implemented the first two suggestions as part of the fix. I'll open an issue for creating a right-click menu to add options to in general, since that'll require some more work beyond a quick fix.

**Comment by davish** [comment]
Parts 1 and 2 have been released in `0.1.1`.

**Comment by StefanoRausch** [comment]
Thank you so much!
