### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by bartlomiejnowak94** [davish/obsidian-full-calendar#43]
Hello, 
all the best for this plugin! 
It will be nice to have a better layout for mobile version. It is now impossible to switch in month view and scroll it with finger :(

**Comment by davish** [comment]
Hi @bartlomiejnowak94, thank you for the feature requests! in the future, please try and submit only one request per issue so I can track them easier. I'm closing this issue in favor of #48 and #49 which track your individual requests.
