### ISSUE TITLE
no option to go back to unfold display of tasks like what before 0.10.5 version

### ISSUE THREAD

**Issue by Ravenclawer** [davish/obsidian-full-calendar#437]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/davish/obsidian-full-calendar/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and didn't find any similar reports.

### Expected Behavior

before 0.10.5 all tasks are displayed and no folding of tasks， currently tasks are folded by default 
![image](https://user-images.githubusercontent.com/73892411/230853625-c75a6411-3924-43a2-b28f-d22ec8737c82.png)

and there is no option to go back to previous display mode 
![image](https://user-images.githubusercontent.com/73892411/230853574-10b805b6-4fc8-4968-91af-d6700315b4ab.png)

### Current behaviour

tasks are folded

### JavaScript console output

this is a feature loss, no console report are needed to fix it

### Steps to reproduce

install 0.10.5 version of full calendar plugin and the tasks would unfold

### Calendar information

using notes in a folder as calendar data source

### Which Operating Systems are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] iOS

### Obsidian Version

1.1.16

### Full Calendar Plugin Version

0.10.7

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs.

### Possible solution

Roll back full calendar version to 0.10.5

**Comment by riabac** [comment]
Also finding this a problem with the latest update. Thanks

**Comment by davish** [comment]
Hi @Ravenclawer, thanks for submitting. This was an update to the calendar view, and I don't expect adding an option to get the old view back.

**Comment by Ravenclawer** [comment]
Since you don't expect adding an option to get the old view back, A feature request is redundant for the issue section, I will keep on using version 0.10.5
