### ISSUE TITLE
Google CalDAV wont import - 405 error

### ISSUE THREAD

**Issue by sharetocreate** [davish/obsidian-full-calendar#441]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/davish/obsidian-full-calendar/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and didn't find any similar reports.

### Expected Behavior

Followed the instructions, adding the secret url from a calender to full calendar's url, then putting gmail user & password in, and clicking import.

### Current behaviour

Calendar fails to add / import and comes up with error 405 in top right hand corner of plugin settings screen

### Steps to reproduce

adding the secret url from a calender to full calendar's url, then putting gmail user & password in, and clicking import.

### Calendar information

Full calendar  plugin latest update

### Which Operating Systems are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] iOS

### Obsidian Version

1.1.16

### Full Calendar Plugin Version

0.10.7

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs.

**Comment by davish** [comment]
Hi @sharetocreate, Google Calendar is not supported because it uses OAuth for CalDAV rather than HTTP basic authentication like iCloud, Fastmail and others. This is reported in the documentation: https://davish.github.io/obsidian-full-calendar/calendars/caldav/
