### ISSUE TITLE
Task-events

### ISSUE THREAD

**Issue by blackpeasy** [davish/obsidian-full-calendar#45]
Task-style events would be very useful for time blocking and other cases where you need to know whether the task has been completed within the timeframe or not.

Perhaps using Yaml frontmatter like `task: true` or `taskEvent: true`

![](https://dl.dropboxusercontent.com/s/re22qfa07njf5nj/brave_Ik8QeOFmEH.gif)

**Comment by davish** [comment]
This is a great idea! I already had planned on allowing inline tasks to be included in the calendar as a part of #28, but there's no reason why notes themselves can't be tasks.

In terms of YAML, I would lean towards just using a single `completed: <true|false>` frontmatter field. If `completed` is present at all, the checkbox would be visible.

I'll need to look into how to customize events in the underlying FullCalendar plugin, but a MVP for this would be to add a checkbox to a right-click dialog that I'm planning on adding as part of #7.

**Comment by blackpeasy** [comment]
Great! `completed: <true|false>` Sounds like a smooth solution.

**Comment by wenlzhang** [comment]
It would also be very useful if there can be an option to hide the task from the calendar view when it is completed.

**Comment by AtlcatlQ** [comment]
What about a `completed` variable but with a ISO date? this could be useful if you need to know when you completed the task.

**Comment by AtlcatlQ** [comment]
> > What about a `completed` variable but with a ISO date? this could be useful if you need to know when you completed the task.
> 
> A variable like this would indeed be very useful. Both Dataview and Task Collector support something like this. With Task Collector, one can use something like `[✅] YYYY-MM-DDTHH:mm` to generate a completion suffix like `✅ 2022-03-21T12:00`.
> 
>     * [blacksmithgu/obsidian-dataview: A high-performance data index and query language over Markdown files, for https://obsidian.md/.](https://github.com/blacksmithgu/obsidian-dataview)
> 
>     * [ebullient/obsidian-task-collector: Plugin for https://obsidian.md/ that assists with managing tasks within a document.](https://github.com/ebullient/obsidian-task-collector)

I was talking something more for pages this works but only for to-do lists.

like if you click on the checbox, the field would be added with the current date and time. And if the field is empty or if there is no `completed` field. It should be the same thing as `false` in the boolean

**Comment by wenlzhang** [comment]
> I was talking something more for pages this works but only for to-do lists.

Aha. Indeed, the original feature request was more on a per page basis. My thinking was on a per task basis. 😅

**Comment by davish** [comment]
> > I was talking something more for pages this works but only for to-do lists.
> 
> Aha. Indeed, the original feature request was more on a per page basis. My thinking was on a per task basis. 😅

Support for task lists being included in the calendar is part of #28 😄

**Comment by D4YO** [comment]
> Task-style events would be very useful for time blocking and other cases where you need to know whether the task has been completed within the timeframe or not.
> 
> Perhaps using Yaml frontmatter like `task: true` or `taskEvent: true`
> 
> ![](https://camo.githubusercontent.com/4a21a48c5a5963475b580d854c6656b5f66bf04413f278690b35ac78eb80f521/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f7265323271666130376e6a66356e6a2f62726176655f496b3851654f466d45482e676966)

It would be awesome to have a such feature 😍

**Comment by ljantzen** [comment]
I'd prefer some kind of integration with the obsidian-task-plugin.  Currently I add a #task entry in the calendar note after the frontmatter, but it is basically duplicating the information, which seems unneccesary.

**Comment by davish** [comment]
@ljantzen are you referring to https://github.com/schemar/obsidian-tasks? If so, then the eventual plan is to support this along with issue #28, which will allow for events to be represented as bullet points.

**Comment by ljantzen** [comment]
Yes, that's the one. 👍

**Comment by drannex42** [comment]
> Task-style events would be very useful for time blocking and other cases where you need to know whether the task has been completed within the timeframe or not.
> 
> Perhaps using Yaml frontmatter like `task: true` or `taskEvent: true`
> 
> ![](https://camo.githubusercontent.com/4a21a48c5a5963475b580d854c6656b5f66bf04413f278690b35ac78eb80f521/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f7265323271666130376e6a66356e6a2f62726176655f496b3851654f466d45482e676966) [ ![68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f7265323271666130376e6a66356e6a2f62726176655f496b3851654f466d45482e676966](https://camo.githubusercontent.com/4a21a48c5a5963475b580d854c6656b5f66bf04413f278690b35ac78eb80f521/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f7265323271666130376e6a66356e6a2f62726176655f496b3851654f466d45482e676966) ](https://camo.githubusercontent.com/4a21a48c5a5963475b580d854c6656b5f66bf04413f278690b35ac78eb80f521/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f7265323271666130376e6a66356e6a2f62726176655f496b3851654f466d45482e676966) [ ](https://camo.githubusercontent.com/4a21a48c5a5963475b580d854c6656b5f66bf04413f278690b35ac78eb80f521/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f7265323271666130376e6a66356e6a2f62726176655f496b3851654f466d45482e676966)

Any movement on this? This sounds like such a great idea!

**Comment by davish** [comment]
Currently on a bit of a bug-bashing spree, but I might pick this up relatively soon.

**Comment by davish** [comment]
Looks like there’s a way to customize rendering of events which can be used to render checkboxes: https://fullcalendar.io/docs/event-render-hooks
