### ISSUE TITLE
Full Calendar timezone per event

### ISSUE THREAD

**Issue by treardon17** [davish/obsidian-full-calendar#451]
### Submit on Discussions

- [X] I will submit my feature request as a [Discussion](https://github.com/davish/obsidian-full-calendar/discussions/new?category=feature-requests).

I'm using obsidian to track my travels. There are several times where the events and times are in different timezones/countries. The way the date information is stored currently is not conducive to multi-timezone calendars because it tracks the `date`, `startTime`, and `endTime` without including the UTC offset. I think it would be very helpful to store all of the required information in ISO8601 format in two fields: `startTime` and `endTime`, with `endTime` being optional. The `startTime` field would include the date, time, and UTC offset (or just the date if the event is marked as all day). I know there's an existing timezone FR (https://github.com/davish/obsidian-full-calendar/discussions/358) but it deals with remote calendars instead of local calendars.

I would be particularly interested if a custom template could be used (which I understand would likely be a separate feature request, or a duplicate of https://github.com/davish/obsidian-full-calendar/discussions/396). A custom template would allow my activities to have a location, participants, a description, and attached files (like tickets for events).

**Comment by davish** [comment]
Hi @treardon17, please submit feature requests as Discussions, like the template says. I will not be looking at discussions in the Issues tab.

**Comment by treardon17** [comment]
@davish my bad! I misunderstood the instructions, sorry about that.
