### ISSUE TITLE
Automatically Scheduling Tasks

### ISSUE THREAD

**Issue by dojoteef** [davish/obsidian-full-calendar#46]
This plugin is great! Thanks for making it. Once you get tasks displaying on the calendar I’m interested in automatically scheduling them similar to
[Skedpal](https://www.skedpal.com/how-it-works/).

I’m not sure what the best approach is for accomplishing this. Is there a way to leverage dataview blocks as a way to schedule tasks?  Should I make my own plugin that provides scheduling capabilities for putting tasks into the calendar?

What are your thoughts?

**Comment by davish** [comment]
Hi @dojoteef, thanks for the feature request! Unfortunately, I don't think that auto-scheduling is something that I see as within the scope for this project. It's certainly an awesome idea and I think could be created as a complementary plugin or user script using QuickAdd and MetaEdit. I'm closing this issue, but feel free to let me know if you have any other questions or suggestions.

Cheers!

**Comment by dojoteef** [comment]
Hi @davish, sorry if I wasn’t clear. I was not requesting that you implement auto scheduling. Rather I was asking, when you introduce scheduling for tasks, what (if any) API will you expose that will allow for scheduling tasks? Are tasks simply going to be displayed on the calendar via a Dataview block, or will you expose some dedicated API for scheduling tasks onto the calendar?

**Comment by davish** [comment]
Ah I see. Tasks will be represented as part of existing Vault notes, just like events are represented now. I'm not sure what the exact format will be, but it'll either be with inline Dataview fields or YAML frontmatter.
