### ISSUE TITLE
Full Calendar tab is blank in every version after the 0.8

### ISSUE THREAD

**Issue by pat-div-kb** [davish/obsidian-full-calendar#460]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/davish/obsidian-full-calendar/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and didn't find any similar reports.

### Expected Behavior

Visualize and use the Full Calendar tab

### Current behaviour

The Full Calendar tab is blank. I realized that the problem occurs in all the versions that follows the 0.8

### JavaScript console output

This comes in the last version installed:

![Screenshot_2023-06-03_12-02-09](https://github.com/davish/obsidian-full-calendar/assets/103312812/b3e0d9dd-ad01-4de7-b496-bd95b118d955)

### Steps to reproduce

Lunching Obsidian Full Calendar

### Calendar information

I have 4 remote Google Calendar and 1 local calendar. Everything works in the version 0.8.0 

### Which Operating Systems are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Android
- [ ] iOS

### Obsidian Version

1.3.5 (and some previous one... I have this problems since few months)

### Full Calendar Plugin Version

all the versions that follows the 0.8

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs.

### Possible solution

Downgrading to the version 0.8.0

**Comment by alexbevi** [comment]
Confirmed on Windows as well

**Comment by Grant837** [comment]
I am not sure this is the same problem, but I have one (secondary) Windows PC that suddenly does not show any of my full note events... on my android, ipad, and another windows PC, all is OK.  I use Sync, so replication should not be the problem, should it?

**Comment by pat-div-kb** [comment]
> I am not sure this is the same problem, but I have one (secondary) Windows PC that suddenly does not show any of my full note events... on my android, ipad, and another windows PC, all is OK. I use Sync, so replication should not be the problem, should it?

As long as I can tell I would say the problem is the same. I confirm that also in my case Full Calendar  works properly in the Android app.

**Comment by inefg** [comment]
关闭所有插件，依次启动 Full Calendar 和其它插件，确保先启动 Full Calendar 。之后就能加载出来的了

**Comment by Phil-T1** [comment]
Same for me in android, entirely blank after successfully linking five Google calendars.

Thanks,

Phil.

**Comment by berlincount** [comment]
This bug actually seems to actually be #233 ...

**Comment by pat-div-kb** [comment]
> This bug actually seems to actually be #233 ...

Yes, I can confirm... I solved the problem removing the plugin "Itinerary"! However now I got the issue  #481
