### ISSUE TITLE
Error parsing time string '23:00:22': unparsable'

### ISSUE THREAD

**Issue by tsbertalan** [davish/obsidian-full-calendar#496]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/davish/obsidian-full-calendar/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and didn't find any similar reports.

### Expected Behavior

All ICS calendar data should load, and items with extra details (like seconds) should degrade gracefully.

### Current behaviour

Some events seem to raise errors, and may be dropped.

### JavaScript console output

```
plugin:obsidian-full-calendar:62470
FC: Error parsing time string '23:00:22': unparsable'
parseTime @ plugin:obsidian-full-calendar:62470
```

### Steps to reproduce

I'm not really sure, since the debug output doesn't give me enough searchable details for the event.

### Calendar information

I'm loading 13 Google Calendar calendars using their private URLs. Actually, as far as all of the events are missing from one of the URLs, and there are other blocking issues like the [various timezone issues](https://github.com/davish/obsidian-full-calendar/issues?q=is%3Aissue+timezone) that apply unpredictably to some, but not all, of my loaded events.

### Which Operating Systems are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] iOS

### Obsidian Version

1.4.5 installer 1.3.5

### Full Calendar Plugin Version

0.10.7

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs.

### Comments

I haven't reloaded the UI without other plugins since that would take several minutes, very likely give the same result, and then have to be undone, taking another several minutes (due to Obsidian's slow loading).

**Comment by davish** [comment]
Should be fixed by PR #484 which was just merged.
