### ISSUE TITLE
Renaming of Events Is not Propagated

### ISSUE THREAD

**Issue by StefanoRausch** [davish/obsidian-full-calendar#5]
I have tried the following:

1. Renaming of the event in the modal. It changes the title property in the YAML-FM of the event but does not change the file name.
2. Renaming of the event's file name. It does not rename the event in the FC view.

It would be great if you could implement both approaches.

**Comment by davish** [comment]
Hi @StefanoRausch, thanks for filing this issue! You're right that the title of an event should stay in sync with the title of its backing note as much as possible. I'm concerned about filename collisions, though, so fixing this issue would include adding logic about how to handle name conflicts as they arise. This will be a longer term fix, but I'll keep track of it!
