### ISSUE TITLE
Sync Todoist tasks into calendar view

### ISSUE THREAD

**Issue by wenlzhang** [davish/obsidian-full-calendar#54]
It would be great if tasks from reminder apps like Todoist can be synced into Full Calendar. Ideally, two-way sync would be great, just like the feature request for two-way sync between Google Calendar and Obsidian.

If two-way sync is not possible, then the option to create a note for the synced Todoist task would also be very useful, just like the following request: https://github.com/davish/obsidian-full-calendar/issues/40

**Comment by dojoteef** [comment]
The plugin supports `.ics` files, so I believe this should work:
https://todoist.com/help/articles/use-todoist-with-your-calendar

**Comment by wenlzhang** [comment]
Thanks for the hint! This does sync Todoist tasks into Full Calendar as calendar events.

It would be even better if Todoist tasks can be synced into Full Calendar with the following features:

- There would be a checkbox preceding the task text.
- One can click the checkbox to complete tasks, and then they would then disappear from Full Calendar and Todoist.
- The synced Todoist tasks would be automatically moved to Today view when they are due, while their original due date does not change.
    - This is how the Fantastical app handle Todoist tasks that are due.

**Comment by davish** [comment]
Thanks for submitting this feature request! Unfortunately, a full, two-way integration with todoist will likely be out-of-scope for this plugin for the forseeable future. Two-way sync with Todoist is definitely behind in priority to two-way sync with Google Calendar (#25), and would probably be a similar amount of effort.

Hopefully by combining the existing Todoist sync plugins, Full Calendar will be able to work better with Todoist tasks once it's possible to add tasks to events (#45) and checkboxes can be rendered in the calendar.
