### ISSUE TITLE
Event becomes an event w/ multiple days if created in monthview

### ISSUE THREAD

**Issue by MajorEnkidu** [davish/obsidian-full-calendar#55]
**Describe the bug**
An event created in the month view becomes an event with multiple days, if a custom duration is put in, even if the duration doesn't exceed the day.

In short the endDate isn't set correctly.

**To Reproduce**
1. Go to the month view
2. Insert an event name
3. Uncheck the "All day event" checkbox
4. Insert a custom start and endtime
5. Click on save
6. Now the endDate in the frontmatter is set to the day after the event.

**Expected behavior**
The endDate should be the same as the start date.

**Console Errors**
No errors are printed to the console.

**Device info (please complete the following information):**
 - OS: Windows 11
 - Plugin Version: 0.5.1

**Comment by davish** [comment]
Thanks for the bug report! This is due to how FullCalendar represents all-day events. I'll work to either fix this issue outright or also add an "end date" field to the modal so that this can be edited in-line rather than manually in the yaml.

**Comment by mileshuskey** [comment]
I am experiencing this identically, except for the following:

OS: Ubuntu 20.04
Plugin Version: 0.5.3
