### ISSUE TITLE
Event disappears from calendar after clicking save event

### ISSUE THREAD

**Issue by zsviczian** [davish/obsidian-full-calendar#57]
I have a reoccurring event on my calendar. When I open the event properties and make some changes such as the timing of the event or the title of the event, and then tap save, the event is no longer displayed on the calendar page. When I reopen the calendar the event is there again (with all the updates correctly saved)

**Comment by davish** [comment]
Hi @zsviczian, thanks for the bug report! Can you check your JS console and see if anything is printed out after hitting Save?
