### ISSUE TITLE
Integration with periodic_notes

### ISSUE THREAD

**Issue by GdeJoode** [davish/obsidian-full-calendar#6]
It would be a nice feature to have the calendar link to the periodic-notes plugin. Opening / creating a daily note when clicking a specific day, weekly note when clicking week, etc.

**Comment by WychWitch** [comment]
I would love this!! I would also love for some functionality of scraping event information *from* the daily notes! Of course it wouldn't have the full amount of capabilities of a full event page, (dragging and dropping would probably be a pain to enable) but being able to quickly add an event name, start and end time within for a day would be amazing.

Maybe it could be a simple piece of YAML frontmatter? Or even a specific kind of formatting, such as:

`@Event: Event Name goes here, 00900-1400`

That way you can easily add stuff to your daily note as you go, set up automatically recurring events as part of the daily-note template workflow, and making future daily notes even more productive!

if this isn't feasible that's totally understandable!

**Comment by pcause** [comment]
I use the itinerary plugin for this.  you can have a periodic note and insert a template that sets this up.  you can have it pull events from the day note or specify external files to pull events from.  author of this plugin might look there for ideas.  for example they have a source entry for config which is a list of files to look at for event entries.

**Comment by GdeJoode** [comment]
This could also be interesting, but my request is of a simpler kind: from
the calender view click a date/week/month and open or create the
corresponding periodic note.

I did not know the Itinerary plug-in which for me has some nice features.
So thank you for that.

Op vr 18 feb. 2022 om 22:15 schreef pcause ***@***.***>

**Comment by davish** [comment]
@wychwitch I moved your request to its own issue and added some of my own elaboration: #28

**Comment by davish** [comment]
@GdeJoode I also think you should look into the [Calendar plugin](https://github.com/liamcain/obsidian-calendar-plugin) for a deep integration with periodic-notes. This plugin isn't aiming to replace that plugin, which is described as "a simple Calendar view for visualizing and navigating between your daily notes", rather than a way to view events during the day.
