### ISSUE TITLE
Create notes for synced events

### ISSUE THREAD

**Issue by chuckharmston** [davish/obsidian-full-calendar#68]
I'd love to be able to create notes associated with events on synced calendars, potentially using the ics `UID` property as a frontmatter field to create that association. Some use cases for this are relatively obvious: taking meeting notes, capturing action items from events, etc.

Some of the features this might permit:

1. Hover-to-preview notes for synced events.
2. Clicking on synced events to open up the notes
3. Using dataview with notes for synced events, e.g. a dataview block in a periodic note template to list all the meeting notes for events in that day

**Comment by davish** [comment]
Thanks for sumitting this, @chuckharmston! This request is already tracked in issue #40, and it's the next big feature on my to-do list. I'm closing this issue, but feel free to keep an eye on #40 to stay up-to-date.

**Comment by chuckharmston** [comment]
Thanks @davish, missed that in my search.
