### ISSUE TITLE
Add right-click context menu on events

### ISSUE THREAD

**Issue by davish** [davish/obsidian-full-calendar#7]
Perform actions on events by right-clicking, like
- Delete event
- Open note
- Move event (once multiple calendars is added)
- Open daily / weekly / monthly note: #6

**Comment by HEmile** [comment]
> Open daily / weekly / monthly note: https://github.com/davish/obsidian-full-calendar/issues/6

Hi, this is very important for my use case, see #59 . Are you also planning to allow hovering over these links and creating a popover, which allows editing with Hover Editor?
