### ISSUE TITLE
Source Code License

### ISSUE THREAD

**Issue by dojoteef** [davish/obsidian-full-calendar#75]
Considering I'm working on a pull request right now, it seems prudent to make sure I understand what license you're releasing the source code under. Could you please add a LICENSE or LICENSE.md file to the repo?

If you're unsure which license to go with, might I recommend the MIT license or the BSD 2 or 3 clause licenses?

**Comment by davish** [comment]
Thanks @dojoteef! Another oversight of starting this repository with a template. I generally use the MIT license for my projects, and just added it to the repository. Cheers!
