### ISSUE TITLE
Feature request: option to parse sub-folders for events

### ISSUE THREAD

**Issue by zsviczian** [davish/obsidian-full-calendar#8]
This is a VERY PROMISING plugin. Thanks for developing it.
I have my meeting notes organized in folders. Would be great if I could add the frontmatter metadata to any note in my vault and the calendar would pick it up.

**Comment by davish** [comment]
Thanks for the feedback, and thanks for filing this feature request! I'm working on allowing multiple calendars based in multiple folders, it shouldn't be too hard to add an option for some calendars to recursively search their child folders for events.

**Comment by zsviczian** [comment]
🎉

**Comment by davish** [comment]
I'll follow up on this thread when I cut the next releaase 😄
