### ISSUE TITLE
Feature request: Add support for plain text events

### ISSUE THREAD

**Issue by blackpeasy** [davish/obsidian-full-calendar#9]
For small events like "go for a run" It seems a bit excessive to create a whole note just for that purpose.

Would be nice to have the option of adding calendar entries that are simply text. 
Entries that don't have to point to a note in the vault.

**Comment by pcause** [comment]
You might look at how the itinerary plugin defines events.  it allows multiple events to exist in a note.  actually if you start by using that format and enhance it, you'll be able to convert users of that plugin.  itinerary doesn't support the recurring events, but they do support coloring (background and text) in an event.  that plugin also uses the full-calendar library to show the calendar and supports the different formats.

**Comment by davish** [comment]
I don't think supporting events with no backing in the Vault will be supported. Like @pcause mentioned, multiple inline events within a single note might cover your concerns, and since it's described in #28, I'm closing this issue in favor of that one.
