### ISSUE TITLE
Save Event button does not respond to clicking

### ISSUE THREAD

**Issue by DanielYehezkeli** [davish/obsidian-full-calendar#99]
When using an ICS Connection to my Google calendar (Using ICS), events are being pulled properly, but I cannot create a new event. The Window is opened but it adds a tiny window between the name of the event and the time, which looks like a bug. When clicking on -Create event nothing seems to happen, and the window stays as it was. 

It could happen because ICS is a one way protocol, but there should be at least an error message for it since not everybody knows that. 

**To Reproduce**
1. Create an event in an ICS format Calendar
2. name the event
3. Press the weird arrow below the event name - an odd window opens out of view
4. Click on save event
5. See error

**Expected behavior**
The arrow will open an out-of-view little window, the save button will do nothing 

**Screenshots**
![image](https://user-images.githubusercontent.com/50593522/164479818-17295696-a503-4054-b023-9523cd697efa.png)

**Console Errors**
I couldn't find the developer tools to use, I apologize.

**Device info (please complete the following information):**
 - OS: [Windows 10]
 - Plugin Version [e.g. `0.6.1`]

Thank you!

**Comment by davish** [comment]
Hello @DanielYehezkeli,

ICS Calendars are currently read-only. Please add a local calendar if you would like to create calendars.

Thanks for submitting the issue! I'll close this out.
